### ISSUE TITLE
stickers not detectable on Android 4.4

### ISSUE THREAD

**Issue by tcpctvgp** [Estimote/Android-SDK#103]
I downloaded the estimote android app from the play store and it doesn't detect any estimote sticker.  Tested with iOS and it works.

**Comment by romainbraun** [comment]
+1

**Comment by cmaier** [comment]
Version 0.9.2, Release Notes: `With this release we add support for Estimote Stickers, [...]`

[Google Play Store Estimote App](https://play.google.com/store/apps/details?id=com.estimote.apps.main)

Haven't tried it yet, but I will later.

**Comment by wiktor** [comment]
@cmaier That's correct :). We will be updating SDK shortly.
