### ISSUE TITLE
onBeaconDiscovered-results in non-ui thread

### ISSUE THREAD

**Issue by RediOne1** [Estimote/Android-SDK#104]
When writing, my application, I noticed that the main thread blocks, when method `onBeaconDiscovered` doing more work. In `onBeaconDiscovered` I wrote this:
```java
@Override
public void onBeaconsDiscovered(Region region, final List<Beacon> beacons) {
	if(Looper.myLooper() == Looper.getMainLooper())
		Log.d("DEBUG_TAG", "MainThread");
	else
		Log.d("DEBUG_TAG", "SeparateThread");

		...
}
```
to check, if the results are delivered on non-ui thread, as it is writen in sample code in documentation:
```java
@Override
public void onBeaconsDiscovered(Region region, final List<Beacon> rangedBeacons) {
    // Note that results are not delivered on UI thread.
    runOnUiThread(new Runnable() {
     ...
```
but the results of log was "MainThread".
I'm using beaconManager in custom service, which is working even the app is closed, or phone is restarted. It is possible to recive `onBeaconDiscovered` results in non-ui thread, or it is something wrong in my code.
This is my simplified `Service` code:
```java
import android.app.Service;
import android.content.Intent;
import android.os.IBinder;
import android.os.RemoteException;
import android.util.Log;

import com.estimote.sdk.Beacon;
import com.estimote.sdk.BeaconManager;
import com.estimote.sdk.Region;

import java.util.List;
import java.util.concurrent.TimeUnit;

public class MyBeaconScanner extends Service implements BeaconManager.MonitoringListener, BeaconManager.RangingListener {

	private static final Region ALL_ESTIMOTE_BEACONS = new Region("regionId", null, null, null);

	private static BeaconManager beaconManager = null;

	@Override
	public int onStartCommand(Intent intent, int flags, int startId) {
		if (beaconManager == null)
			startMonitoringService();

		return Service.START_STICKY;
	}

	private void startMonitoringService() {
		beaconManager = new BeaconManager(this);
		beaconManager.setBackgroundScanPeriod(TimeUnit.SECONDS.toMillis(1), 0);
		beaconManager.setMonitoringListener(this);
		beaconManager.setRangingListener(this);
		beaconManager.connect(new BeaconManager.ServiceReadyCallback() {
			@Override
			public void onServiceReady() {
				try {
					beaconManager.startMonitoring(ALL_ESTIMOTE_BEACONS);
				} catch (RemoteException e) {
					Log.e("BEACONS", "Cannot start ranging", e);
				}
			}
		});
	}

	@Override
	public void onDestroy() {
		super.onDestroy();
		try {
			beaconManager.stopMonitoring(ALL_ESTIMOTE_BEACONS);
			beaconManager.stopRanging(ALL_ESTIMOTE_BEACONS);
		} catch (RemoteException e) {
			Log.e("BEACONS", "Cannot stop but it does not matter now", e);
		}
		beaconManager.disconnect();
		beaconManager = null;
	}

	@Override
	public void onBeaconsDiscovered(Region region, final List<Beacon> beacons) {

		doSomething();
	}

	@Override
	public void onEnteredRegion(Region region, List<Beacon> beacons) {
		beaconManager.connect(new BeaconManager.ServiceReadyCallback() {
			@Override
			public void onServiceReady() {
				try {
					beaconManager.startRanging(ALL_ESTIMOTE_BEACONS);
				} catch (RemoteException e) {
					Log.e("BEACONS", "Cannot start ranging", e);
				}
			}
		});
	}

	@Override
	public void onExitedRegion(Region region) {
		try {
			beaconManager.stopRanging(ALL_ESTIMOTE_BEACONS);
		} catch (RemoteException e) {
			e.printStackTrace();
		}
	}

	@Override
	public IBinder onBind(Intent intent) {
		return null;
	}

	
}
```

**Comment by wiktor** [comment]
Which Android version?

**Comment by RediOne1** [comment]
5.0

**Comment by wiktor** [comment]
This is regression on Android 5, before it wasn't delivered on UI thread. Fixing this will take a bit more time.

**Comment by Malivuk** [comment]
Hello,

I have the same problem here. I work on 5.1
Any news?

**Comment by wiktor** [comment]
@Malivuk 
Not yet. Note that this is not crucial or introducing any bugs. This will not cause any problems in your app.

**Comment by Malivuk** [comment]
Sure there is no bug but my app relies on a background service that detects if someone stay nearby a beacon area for few minutes.

I'm afraid there is no workaround for me.

**Comment by wiktor** [comment]
@Malivuk 
There is a workaround. When callback is invoked like `onBeaconsDiscovered` just invoke code block in a background thread and that's perfectly fine.

Can you elaborate why invoking it on main thread causes problem for you?

**Comment by Malivuk** [comment]
Ok I'll try some different ways. I was just trying to follow some best practices and put all my beacon related code into a service but maybe I'm wrong.

**Comment by manoj192** [comment]
@Malivuk 
       
        beaconManager.setRangingListener(this) does't give result for specific device(Micromax q439) i checked SystemRequirementsChecker.checkWithDefaultDialogs(HomeActivity.this) also .

 Note : my region request   private static Region BEACONS= new Region("regionId",
            null, null, null);

            Android 6
