### ISSUE TITLE
Documentation Bug

### ISSUE THREAD

**Issue by mjkaufer** [Estimote/Android-SDK#109]
Hey all,

There's a bug in the documentation. I talk about it in this pull request: https://github.com/Estimote/Android-SDK/pull/108

Basically, the docs say to use `EstimoteCloud.get()`, but that's not a command, and the user should instead use `EstimoteCloud.getInstance()`.

**Comment by wiktor** [comment]
I fixed that in our source code, it will be live for the next release. I'll close this bug when new release occurs.
