### ISSUE TITLE
Background service & Indoor SDK

### ISSUE THREAD

**Issue by adnan-SM** [Estimote/Android-SDK#110]
So I am trying to figure out how to make sure that the beacon is discovered even with the app closed. The best approach seems to be running a service in the background and monitoring the beacons from there. But this seems to work for few and not work for others. Is there any particular thing I should know about ? Will having a service running in the background and monitoring the beacons work ?

Also, the Indoor SDK for Android is supposed to be coming out later this year if not next, any updates regarding the same ? We are planning to deploy Estimotes at over 1000 venues each having arnd 10 beacons minimum. But the major functionality we want relies heavily on how accurate we can navigate the users indoors at the venue, so any updates/time-frame would be appreciated.

Thanks

**Comment by wiktor** [comment]
Monitoring works out of the box. Regarding app closed state please refer to [thread on our forums](https://forums.estimote.com/t/background-notification-possible-on-android/1028).

We do not comment about Indoor Android SDK at the moment.
