### ISSUE TITLE
Unable to Connect to Beacon

### ISSUE THREAD

**Issue by achusuresh2** [Estimote/Android-SDK#111]
When trying to run the Change Beacon's Minor Demo, the application is unable to connect to the beacon and fails with the error, "Read Timed Out." I did make sure to update the AppID and AppToken from those in my EstimoteCloud account.

**Comment by wiktor** [comment]
@achusuresh2 Can you drop me an email at wiktor (at) estimote (dot) com so we can look directly with your credentials?

**Comment by wiktor** [comment]
Fixed in 0.6.1.
