### ISSUE TITLE
What to expect re: Android Nearables support?

### ISSUE THREAD

**Issue by anulman** [Estimote/Android-SDK#113]
Hi Estimote!

I'm working on an Android project using Beacons now, and the client asked if we could also support Nearables. Noticed that Nearables are not yet part of the Android SDK & don't seem to be otherwise mentioned in this repo; is there anything you can share re: roadmap? I'd love to offer them an educated answer.

Keep up the good work :+1:

**Comment by wiktor** [comment]
We have just update our Estimote app in Play Store with Nearables support. Expect SDK update in couple of days.

**Comment by anulman** [comment]
Thanks! Looking forward to the update

**Comment by wiktor** [comment]
Released: https://github.com/Estimote/Android-SDK/releases/tag/0.7
