### ISSUE TITLE
android.hardware.bluetooth_le shouldnt be required=true

### ISSUE THREAD

**Issue by onskulis** [Estimote/Android-SDK#114]
There might be people (I guess im not the only one), who would like to support devices with their applications, which has no Bluetooth LE protocol. Estimote Beacons might be a feature of an application which would be available for those devices with LE protocol. Our application cannot support over 3000+ devices from like 7000+ which were supported, just after setting dependency for estimote SDK. I think its a big issue.

**Comment by wiktor** [comment]
Please do check most recent release of library. This requirement was dropped.

Now it is:
```
  <uses-feature android:name="android.hardware.bluetooth_le" android:required="false"/>
```

**Comment by wiktor** [comment]
I updated CHANGELOG to make it explicit.

**Comment by onskulis** [comment]
Thank you.

**Comment by heart** [comment]
if you want to make your app available to devices that don't support BLE, you should still include this element in your app's manifest, but set required="false"

Then at run-time you can determine BLE availability by using PackageManager.hasSystemFeature():

    // Use this check to determine whether BLE is supported on the device. Then
    // you can selectively disable BLE-related features.
    if (!getPackageManager().hasSystemFeature(PackageManager.FEATURE_BLUETOOTH_LE)) {
        Toast.makeText(this, R.string.ble_not_supported, Toast.LENGTH_SHORT).show();
        finish();
    }


from : https://developer.android.com/guide/topics/connectivity/bluetooth-le.html

**Comment by wiktor** [comment]
@heart That's correct. Note that SDK does not require BLE anymore, we dropped that requirement.
