### ISSUE TITLE
Two apps conflicting

### ISSUE THREAD

**Issue by joharei** [Estimote/Android-SDK#129]
I have two separate apps, each running their own service as in [this example](https://github.com/knowledgetranslation/BeaconPlaygroundAndroid). App 1 only does monitoring, while App 2 also does monitoring, but starts ranging once once inside a region if the app is in the foreground. 

The monitoring works as expected for both apps, but when I open App 2 so that it starts ranging, App 1 receives `onExitedRegion`, and does not react until I stop the ranging in App 2. 

Using Estimote SDK 0.9.1 on Android 6.0 (had the same problem in 5.1.1).

Please tell me if I can provide more debug info.

**Comment by wiktor** [comment]
Thanks @joharei for reporting that. It looks very interesting and I'll be taking closer look into that.

**Comment by whollacsek** [comment]
Hello @pawelDylag is this issue fixed? If so in which version of the SDK?

**Comment by pawelDylag** [comment]
Hello @whollacsek 

It should be fixed in version 1.0.0 - we did some fixups with background service communication. 
Please let me know if this still occurs for you - if so, we will dig deeper into it :)

Have a nice day!

**Comment by whollacsek** [comment]
I'll let you know, thanks.
