### ISSUE TITLE
App stuck when ranging all beacons second time

### ISSUE THREAD

**Issue by HMMakadiya** [Estimote/Android-SDK#133]
Device : Lenovo A6000
Android Version 4.4.4

First time ranging work properly close app and restart again.

com.estimote.sdk.service.internal.JellyBeanBluetoothAdapter.start:48 Bluetooth adapter did not start le scan

12-03 16:37:19.133 4017-4041/com.example.airport D/BluetoothAdapter: startLeScan(): null
12-03 16:37:29.143 4017-4041/com.example.airport A/EstimoteSDK: com.estimote.sdk.service.internal.JellyBeanBluetoothAdapter.start:48 Bluetooth adapter did not start le scan
12-03 16:37:29.153 4017-4041/com.example.airport D/EstimoteSDK: com.estimote.sdk.service.internal.CycleBluetoothScanner.start:65 Could not start Bluetooth scanning
12-03 16:37:30.163 4017-4041/com.example.airport D/BluetoothAdapter: stopLeScan()

I faced same issue in your app also
![device-2015-12-03-171115](https://cloud.githubusercontent.com/assets/14011009/11559708/fc9b8940-99e0-11e5-9ff8-12c1c03c5069.png)

**Comment by martinklimek** [comment]
Hi @HMMakadiya,

Thanks for this report. This issues is strictly related to unstable bluetooth stack on android devices. We do not have any control over this, unfortunately. We do some tricks to avoid this kind of issues, though. You can try to update your project with latest SDK to check if our latest fixes helped. 

Another idea is update Android version on your device. As far as I can update to Lollipop 5.0 is available starting from September 2015. 

Hope it helps.
Marcin
