### ISSUE TITLE
java.lang.NullPointerException when using SDK on Emulator

### ISSUE THREAD

**Issue by homtec** [Estimote/Android-SDK#134]
When using the SDK on the standard Android emulator, you get a NullPointerException as BluetoothAdapter is not present.

java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.BluetoothAdapter.isEnabled()' on a null object reference

**Comment by Poberro** [comment]
This issue is fixed in SDK release 0.9.6

**Comment by homtec** [comment]
:+1:
