### ISSUE TITLE
Beacons not detected on Moto G 3rd gen and Android 5.1.1

### ISSUE THREAD

**Issue by centos94** [Estimote/Android-SDK#136]
Hello,
I'm developing an app based on your Android-SDK using only ranging.
After your answer to the topic 
https://github.com/Estimote/Android-SDK/issues/135
I tested on more devices to search a specific problem and then I found issues on Android 5.1.

I tested on:
- Samsung Galaxy S6 (Android 5.1.1)
- Motorola G (Third Generation) (Android 5.1.1)

And this devices had different problems, but only that with Android 5.1.1 'cause on Nexus 5 (/w Android 6.0) everything worked correctly.

The issues i've encountered is:
- Samsung Galaxy S6: I can't show the distance. Device found the beacons but not the RSSI.
- Motorola G (Third Generation): everything is on(bluetooth, localization), but beacons aren't found.
Even with your application downloadable from Google Play.

Then I tryied with another library and with that I can see all beacons. 

Have you a patch to this problem?
Any suggestion?

Thanks in advance

**Comment by heypiotr** [comment]
Thanks for the extra info. So it looks like your Galaxy S6 issue is actually #135—we're already looking into solving that. The Moto G issue is a new one, so we'll dive into it next.

**Comment by centos94** [comment]
@heypiotr after some other tests, with that string, I solved the problem.
In both devices.

Thank you for your support.

**Comment by jitongkai** [comment]
I had found this problem in MeiZu pro5, can not find any beacons! how to fixed it.

**Comment by heypiotr** [comment]
Great to hear that @centos94! Feel free also try the latest version of the SDK and app, we fixed a great deal of bugs related to beacon discovery.

@jitongkai, please open a separate bug report and provide more details: version of Android OS, have you tried the app and the SDK, which versions of the app and the SDK, etc. Please also make sure to re-check with the latest versions—as I mentioned above, we fixed a few bugs just this week.

**Comment by agiratech-sankar** [comment]
Hi Team,
   I tested beacon app on moto c plus, sometimes it's not detecting the beacons or takes too much time. Currently, am using this sdk 'com.estimote:sdk:1.4.5'.
