### ISSUE TITLE
Exited region is called every second after firmware upgrade of Beacons

### ISSUE THREAD

**Issue by manoj2791** [Estimote/Android-SDK#145]
I have developed an app that will monitor the entry and exit of rooms based on beacon's presence. It was working fine till the upgrade of Beacon's firmware. After I upgraded, I started to receive many exited region call and in logs I see, that the beacon was emitting signal with 2 or 3 secs delay.

And in the demo app provided with this, when I clicked notify demo for a particular beacon, it started to give me one entered region and multiple exited region and the exited region happens immediately after entered region is triggered. Because of this, I was not able to track any users in a room.

**Comment by pawelDylag** [comment]
Hello @manoj2791 ! 
In order to start investigating, we need you to give us some more detailed information about your software. Please tell us about your SDK version, beacon firmware (you can check that by connecting to that beacon) and phone you are using. 

Have a nice day!

**Comment by martinklimek** [comment]
Any news @manoj2791 ?
