### ISSUE TITLE
How to get MeasuredPower and Rssi after connecting to beacon?

### ISSUE THREAD

**Issue by pawelcala** [Estimote/Android-SDK#146]
Hi there, 
i couldn't find any answer in sdk doc so i'm asking here.
Could you please tell me is it possible to get measured power and rssi ( distance in general ) while i'm connected to beacon? 
I've noticed that after connection is successful RangingListener doesn't return beacon i'm connected with.
Is this proper behavior?

PS. What i want to achieve is to get distance and motion values from beacon. 
Thanks

**Comment by Poberro** [comment]
Yes, this is proper behavior. Proximity Beacons stop advertising when you are connected to them (prevents configuration conflicts). Location Beacons (new ones) still advertise when you are connected to them. They also emit Telemetry packet that has motion information and Location packet that would allow to track distance, so you can avoid having open connection.

**Comment by pawelcala** [comment]
Thanks for response. Still you didn't answer my question how to obtain measured power and rssi. I'm using estimote beacons ( not nearables ). 
Thanks

**Comment by martinklimek** [comment]
HI @pawelcala! 

In general this functionality is not available in SDK for Proximity Beacons (one battery Estimote Beacons). Can you give us a little bit more overview on the app you are building and why you need motion and distance at the same time? 

BTW. What @Poberro mention is that we enabled this kind of use cases with recently release version of beacons (http://blog.estimote.com/post/139902664710/launching-the-most-robust-location-beacons-on-the) where you have access to Estimote Telemetry Packet that gives you motion readings without need of connection.

**Comment by martinklimek** [comment]
Any update @pawelcala ?

**Comment by Poberro** [comment]
In SDK 0.10.1 we added method to obtain RSSI when connected to beacon:
```java
DeviceConnection connection = .....
 connection.readRssi(new SettingCallback<Integer>() {
      @Override public void onSuccess(Integer value) {
    
       }

      @Override public void onFailure(DeviceConnectionException exception) {
        
      }
    });
```

Here is more information how to connect to beacon using `DeviceConnection` class:
https://github.com/Estimote/Android-SDK/blob/master/DOC_deviceConnection.md
