### ISSUE TITLE
computeProximity() seems not to work correctly

### ISSUE THREAD

**Issue by twanschik** [Estimote/Android-SDK#150]
Hi,
I'm testing beacon ranging on Android to see if a beacon is nearby using the test computeProximity() == Proximity.IMMEDIATE. My Beacon is at least 3 meters away (with no obstacles between the beacon and the Nexus 5x) and receives the following signal: measuredPower=-60, rssi=-55. As a result, computeProximity() returns Proximity.IMMEDIATE.

I assumed to get a value of Proximity.IMMEDIATE if the beacon is really nearby i.e. the distance < 0.5m, and otherwise Proximity.NEAR or Proximity.FAR.

Is there something I'm doing wrong? Testing the same beacon with an iOS device returns far better results.

Cheers,
Thomas

**Comment by pawelDylag** [comment]
Hello @twanschik !

There is a difference between RSSI values on different devices. It depends on antenna characteristic, applied filters, and computeAccuracy method itself. Currently we are using a set of constant values measured for Nexus 5 device. For now, they might vary on different phones. We are planning to create set of measured configurations for each device, but well... there are lots of them. There is no such problem on iOS hardware - far less phones to measure :)

Also please notice, that our RSSI is filtered with smoothing filter. It may slightly change reported value. You can turn that off if you want, by using DISABLE_SIGNAL_FILTERING in our sdk. 

We are trying to improve our accuracy, but as you can see, Android is really complicated to deal with  device differences in hardware. 
Let me know what you think! If you have any ideas and suggestions - I look forward to hearing from you :)
