### ISSUE TITLE
Bluetooth Crash - Bluetooth Share has stopped

### ISSUE THREAD

**Issue by scailbc** [Estimote/Android-SDK#153]
Hello everybody,
I'm using the Estimote SDK with an Android device to scan nearby beacons, but for no reason It started to give an error "Blueortooth Share has stopped", the Bluetooth crashes and I can't scan beacons. Shutting down the phone and uninstalling the app didn't work.
Looking in the web I found out that there was a [bug for Android 4.3 and 4.4](https://code.google.com/p/android/issues/detail?id=67272), for which there is a [solution](http://developer.radiusnetworks.com/2014/04/02/a-solution-for-android-bluetooth-crashes.html), and also there is a second [bug in Android 5 and 6](https://code.google.com/p/android/issues/detail?id=191831) solved in the release of March 2016. The difference is that while those bugs completely block the bluetooth, **in my case this affects only the apps using the Estimote SDK**.
I tried to use the [Estimote App](https://play.google.com/store/apps/details?id=com.estimote.apps.main&hl=it) and the error appears, the first time that I use Proximity Demo or Distance Demo it works, then if I exit and enter again I get the error, than if I exit and enter again it works again and if I exit and enter again I get the error again.
In my app the bluetooth never works, maybe because I'm monitoring 15 differents regions (all of them only with UUID).
The app works in other devices, so I'd say that there is some internal status that went wrong and only affects the Estimote SDK, probably the BeaconService.
So, how can I fix and prevent this issue?

The given error is a NoSuchElementException in the BluetoothScanManager, I also got a DeadObjectException, but I think that the first one is the problem. I add the logcat from my app and from the Estimote App, since is probably an internal error I added the whole log that is really long, I tried to color the logs and make the most important bold. For the Estimote App Log there is the full log and at the bottom a second try with only Warning and Error.

[Logcat - Error Unfortunately Bluetooth Share has stopped.docx](https://github.com/Estimote/Android-SDK/files/277493/Logcat.-.Error.Unfortunately.Bluetooth.Share.has.stopped.docx)
[Logcat Estimote App - Error Unfortunately Bluetooth Share has stopped.docx](https://github.com/Estimote/Android-SDK/files/277495/Logcat.Estimote.App.-.Error.Unfortunately.Bluetooth.Share.has.stopped.docx)

This problem in previous version was caused by a great number of MAC address received, in particular the beacons Gimbal (which I use) change MAC every 0.8 seconds and they cause this error.

The device I'm using is an Asus Zenfone 2 with Android API 21.

I know that is really hard to find a solution, since is an internal setting that got errors, but this problem completely destroy my app and any other app using your SDK.
Thanks for your help

**Comment by scailbc** [comment]
Hello, I figured out the problem, it's the number of scanned regions.
As said in [this post](http://stackoverflow.com/questions/29236559/android-bluetooth-low-energy-using-scanfilters), there is a bug in Android 5 that makes the bluetooth crashes if there are too many [ScanFilter](https://developer.android.com/reference/android/bluetooth/le/ScanFilter.html), by reducing the regions from 15 to 5 the  crash doesn't happen.
The bug appeared after updating to build LRX21V.WW-ASUS_Z00A-2.20.40.184_20160504_4658_user_044030427_201501060109 (the only page I found about this release is [this](http://www.asus.com/zentalk/thread-75706-1-1.html), they say "Update Bluetooth FW").
I suppose that the Estimote App too has a good amount of ScanFilter, but still I don't know if there is a reason why only the apps using the Estimote SDK were affected.
Hope this helps

**Comment by pawelDylag** [comment]
Hello @scailbc !

Sorry for the delay. I appreciate your contribution :) Yes, the problem is with too many ScanFilters. If you need to turn off this feature, we have a super secret flag (Just kiddin, not that super secret, but this is not the official way for doing things - rather for debuging):
`
<meta-data android:name="disable_hardware_filtering" android:value="true" />
` 
to your Manifest file inside ``application`` content. It may help with such problems. Anyway, you should update your Android system, because this error was fixed some time ago, as far as I know :)
Have a nice day!

**Comment by scailbc** [comment]
Thanks, it worked. In my manifest I added
`<application`
`        android:allowBackup="true"`
`        android:icon="@mipmap/ic_launcher"`
`        android:label="@string/app_name"`
`        android:theme="@style/AppTheme">`
`        <meta-data android:name="disable_hardware_filtering" android:value="true" />`
Just to know, there are reasons to not add this? Any drawbacks?

**Comment by pawelDylag** [comment]
I'm glad it worked :) 
In general, hardware filtering allows your phone to apply filtering on hardware level. It means, if your phone is in deep sleep (e.x Doze mode), it can filter all results and notify your system only when it has valuable data. Strictly saying, by using this flag you cause some devices (generally with android 5.0+) to drain more battery. But in fact this is the only one drawback, so don't worry - no errors will arise :)
