### ISSUE TITLE
v0.10.8 Analytics are not being sent to the cloud

### ISSUE THREAD

**Issue by Moudi2020** [Estimote/Android-SDK#157]
Analytics are not being sent to the cloud. However, all needed setups is there.
v0.10.8
        EstimoteSDK.initialize(this, Constants.appId, Constants.appToken);
        EstimoteSDK.enableDebugLogging(true);
       // EstimoteSDK.enableMonitoringAnalytics(true);
        EstimoteSDK.enableRangingAnalytics(true);

**Comment by pawelDylag** [comment]
Hello @Moudi2020 !
I'm investigating this issue - thanks for reporting that! 
Some improvements will be made to analytics in next SDK release - should probably solve your problems :)

Have a nice day!

**Comment by pawelDylag** [comment]
Please try SDK version 0.11.0 - some Analytics bugs were fixed there :)
