### ISSUE TITLE
STickers for show room not displayed 

### ISSUE THREAD

**Issue by goodlifechris** [Estimote/Android-SDK#158]
Is it a must to hav e the stickers UUID

**Comment by pawelDylag** [comment]
This is not an Android SDK related issue - as far as I can understand you. Stickers always need to have their UUID as long as they are broadcasting iBeacon packet. Newest firmware is able to broadcast Eddystone URL packet -> http://developer.estimote.com/eddystone/
If you have any questions regarding beacon theory, please contact our support at https://forums.estimote.com/
