### ISSUE TITLE
onBeaconsDiscovered sometimes doesn’t find beacon on Nexus 7 2013 android 6

### ISSUE THREAD

**Issue by kamilwlf** [Estimote/Android-SDK#164]
I've a problem with onBeaconsDiscovered on Nexus 7 2013 android 6.
app sometimes doesn’t find beacon. Beacons are close to the device(1meter).
Could you suggest me a way to ensure that for every scanning I found the beacon?

My code:
```
beaconManager = new BeaconManager(App.getAppInstance());
        region = new Region("ranged region", null, null, null);

@Override
 public void onBeaconsDiscovered(Region region, List<Beacon> list) {
if (!list.isEmpty()) {
   ++countingSuccess;
    //Beacon nearestBeacon = list.get(0);
      if (countingSuccess == 50) {//try 50 times
beaconManager.stopRanging(region);
        }
```

**Comment by pawelDylag** [comment]
Hello @kamilwlf 

Beacon discovery is very dependant on your device's bluetooth stack and hardware.  Also, your beacon advertising interval is also important. If you set your ranging to return results every 1s and your beacon advertising interval to let's say 1200ms, then there is a possible blind spot, when your beacon is not getting discovered throughout whole scanning cycle. 
I suggest you to play with those parameters:
1. Beacon advertising interval - I suggest 200ms for better User Experience
2. Ranging scan cycle time - use `beaconManager.setForegroundScanPeriod()`

Good day to you!

**Comment by kamilwlf** [comment]
How to change advertising interval? Do you mean `setRegionExitExpiration`?

I tried and `setForegroundScanPeriod() ` works!  
result of my test:
after 1sec - random or nothing
after 10sec found 1 beacon
after 20sec found 2 beacons
after 60sec found all 6 beacons

for comparison on galaxy s4 after 1 sec it can detect all beacons

I plan to set beaconManager.setForegroundScanPeriod(20000,0) and Beacon advertising interval 200ms
Previously I used the default settings

**Comment by pawelDylag** [comment]
@kamilwlf 

To change your beacon advertising interval, you need to connect to it via our Estimote App (Can be downloaded from Google Play Store) . Then, you will be able to change it's settings.

Setting `beaconManager.setForegroundScanPeriod(20000,0)` will return results every 20000s - be aware of that. Typical ranging is 1-6s scan time and 0-1s wait time. Bear in mind, that setting shorter scan time will drain your battery much quicker.
