### ISSUE TITLE
Offline configuration option?

### ISSUE THREAD

**Issue by pauldanckaert** [Estimote/Android-SDK#165]
As a feature request, I would like to request an offline configuration much like the other enable flags on the EstimoteSDK object, to disable all network connections and activity. 

When the software is being deployed within an organization or in areas with limited connectivity, the update requests outbound can be a problem, either causing unnecessary logging or undesirable network requests. Although the cloud connection is a huge benefit, it would be good in the SDK to have the option to disable that as needed to avoid potential problems.

**Comment by pawelDylag** [comment]
Hello @pauldanckaert !

For now there is no such possibility - our beacons need to maintain cloud sync at all times. Anyway, we are preparing some functionalities that will help you deal with such problems as you described. Stay tuned :)
