### ISSUE TITLE
How to force open permissions dialog for second time?

### ISSUE THREAD

**Issue by t7ank** [Estimote/Android-SDK#170]
Once  
> SystemRequirementsChecker.checkWithDefaultDialogs(this);

has been called in code, app must be restarted to get it called again. Is there a way to show Estimote dialog on button click?

Thanks.

**Comment by pawelDylag** [comment]
Hello @t7ank 

This is related to: https://github.com/Estimote/Android-SDK/issues/155
All in all, if you want your dialog to be restartable,  you need implement your own functionality. 

Have a nice day!
