### ISSUE TITLE
Beacons scan does not work for API <18

### ISSUE THREAD

**Issue by kamendo** [Estimote/Android-SDK#175]
Is it true that beacons detection does not work for Android API before 18?

From the code it looks like so:
SystemRequirementsHelper.isBluetoothLeAvailable,
SystemRequirementsHelper.isBluetoothEnabled returns false

**Comment by pawelDylag** [comment]
@kamendo Yes, it's true. 

> The Estimote SDK for Android is a library that allows interaction with Estimote beacons & stickers. The SDK system works on **Android 4.3 or above** and requires device with Bluetooth Low Energy (SDK's min Android SDK version is 9).
