### ISSUE TITLE
Change uuid of stickers beacons

### ISSUE THREAD

**Issue by denishamann** [Estimote/Android-SDK#181]
It's not possible for the moment to change the uuid of a sticker beacon even from the cloud or the app (both on Android and iOS). Do you plan to implement it ?
Can you also give me a way to indentify two different beacons without using MAC address?

**Comment by pawelDylag** [comment]
Hello @denishamann 

1.  As far as I know, there is a possibility to change sticker UUID via our Cloud. You need to change its broadcasting packet type to "iBeacon" and that you should be able to modify UUID. Please inform me, if there are any problems with that. 
2. You can set different TAG for each beacon. You can do this via our app, or sdk, or cloud.

**Comment by denishamann** [comment]
Ok thanks, I could change the uuid if I set the iBeacon mode, not if I set the EddyStone mode. I had to change my code a bit to fit with iBeacon mode, it's ok.
I think though there are less options on a sticker estimote than on regular estimote. Also, the iOS app seems to be more complete than the Android one.
