### ISSUE TITLE
Bulk Updater problem

### ISSUE THREAD

**Issue by arslanmustafa** [Estimote/Android-SDK#182]
Trying to run the bulk updater example from the latest version of the SDK. The only change I made was to initialize the SDK with my own app ID and token. In MainActivity.java, I am getting a list of ConfigurableDevice objects from the scan callback. 

`public void onDevicesFound(final List<ConfigurableDevicesScanner.ScanResultItem> devices)`

However, the BulkUpdaterCallback is always returning the onError callback and giving the following LogCat message: 

`12-16 11:33:18.645 7235-7235/com.estimote.bulkupdater W/EstimoteSDK: com.estimote.sdk.connection.scanner.ConfigurableDevicesScanner$1.failure:314 Not starting bulk updater - cannot fetch devices to update
`

**Comment by pawelDylag** [comment]
Hello @arslanmustafa 

It seems like some temporary problem with our Cloud. Could you confirm, that this is still happening?
Also, you can consider switching to our new SDK 1.0.0 with completely new [Bulk Updater](https://github.com/Estimote/Android-SDK/blob/master/Docs/quick_snippets.md#bulk-updater-quick-start) :)
