### ISSUE TITLE
Problem with setForegroundScanPeriod

### ISSUE THREAD

**Issue by matbandeli** [Estimote/Android-SDK#183]
Hello,

I have a problem with the function `setForegroundScanPeriod`.
I would like to scan everey 200ms but it does only every ~1.5 seconds.

If I choose 4000 ms, it works as expected  (it scans every 4 seconds).

My beacons settings :

    Flip to Sleep		ON
    Smart Power Saving	ON
    UUIDs			B9407F30-F5F8-466E-AFF9-25556B57FE6D
    Broadcasting Power	Strong (4dBm)
    Advertising Interval	100 ms

My device :

    Model			Samsung GT-I9505
    Android			6.0.1
    API			23

Here under is the code I use :

    public class MainActivity extends AppCompatActivity {

    private BeaconManager beaconManager;
    private Region region;   

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        
        beaconManager = new BeaconManager(this);

        beaconManager.setForegroundScanPeriod(200, 0);

        beaconManager.setRangingListener(new BeaconManager.RangingListener() {
            double i = 0;
            @Override
            public void onBeaconsDiscovered(Region region, List<Beacon> list) {
                
				Log.d("DEBUG:scan period", ""+i);
				i+= 0.5;    
            }
        });
        region = new Region("ranged region", null, null, null);
    }

    @Override
    protected void onResume() {
        super.onResume();

        SystemRequirementsChecker.checkWithDefaultDialogs(this);

        beaconManager.connect(new BeaconManager.ServiceReadyCallback() {
            @Override
            public void onServiceReady() {
                beaconManager.startRanging(region);
            }
        });

    }

    @Override
    protected void onPause() {
        beaconManager.stopRanging(region);
        super.onPause();
    }   
    }

Thanks for help

**Comment by pawelDylag** [comment]
Hello @matbandeli 

0)  Your "i" variable is incremented by 0.5 every `onBeaconsDiscovered` call. I hope you are not deducing scan time by looking at this value. It's obvious that it will be a sequence (0, 0.5, 1.0, 1.5, ..., n + 0.5). If you want to check estimated time, you need to substract previous call time from current call time. The best temporary solution is to look at LogCat times. 
1) Which version of our SDK are you using?
2) AFAIK Samsung s4 doesn't have any official support for Android 6.0 - therefore some problems might appear with low-level BLE stack.

**Comment by matbandeli** [comment]
Hi pawelDylag
 Thanks for your quick answer.

0. I don't deduce timing with the value of i. The timing was just an estimation.

1. SDK version : 0.9.4 (I'm upgrading to 15.0 and testing)

**Comment by pawelDylag** [comment]
Thanks @matbandeli - good luck with development :) If you have any more problems, let me know!
