### ISSUE TITLE
Problem startMonitoring not have callback in setMonitoringListener ?

### ISSUE THREAD

**Issue by T-Jedsada** [Estimote/Android-SDK#184]

**Comment by T-Jedsada** [comment]
I run example code all not found my becons but Estimote app in store found why?

**Comment by jaydipumaretiya** [comment]
I had same issue? is there any solution And I'm using android os 6.0 and 7.1.1.

**Comment by T-Jedsada** [comment]
Yes i uesed version 6.0.1

**Comment by jaydipumaretiya** [comment]
But If your have 7.0 then?

**Comment by pawelDylag** [comment]
Hello guys, 

In order for me to deduce the exact problem, I need any information from your side - which SDK version you use, type of phone, Android version, any code snippets or any data from debug logs (can be enabled via `EstimoteSDK.enableDebugLogging(true)`)
I would also like to know which example code you are using, @T-Jedsada  - there is a chance that this example is outdated and we forgot to update it. 
I'm waiting for more details, guys!

**Comment by T-Jedsada** [comment]
OK man to day i will send you the information.
