### ISSUE TITLE
Background monitoring is killed and never restarted

### ISSUE THREAD

**Issue by magnusgudmandsen** [Estimote/Android-SDK#186]
Hi! Recently started using Estimote SDK, and I had a few questions regarding a bug we've been having when developing our indoor map application.

First of all, some information:

Device: Samsung Galaxy S7
OS Version: 6.0.1
Estimote SDK version: 0.16.0

My app does the following: Monitors beacons and sends beacon data to a web server for real-time positioning (by closest beacon).

The problem: Beacon background monitoring stops working after a time period (varies, but usually one or a few days). During this time period I usually have time to charge my phone etc, but never restart it. I enter/exit different regions every weekday, many times a day (beacons at the office).

Some code (removed the application-specific code):

```
public class BeaconApplication extends Application implements BeaconManager.MonitoringListener {

    private BeaconManager beaconManager;

    @Override
    public void onCreate() {
        super.onCreate();

        beaconManager = initBeaconManager(new BeaconManager(getApplicationContext()));
    }

    public BeaconManager initBeaconManager(BeaconManager beaconManager) {
        monitoredRegions = new ArrayList<>();

        beaconManager.connect(() -> {
            beaconManagerIsConnected = true;
            fetchRegionsAndStartMonitoring(); // Fetches regions from a database and monitors each region.
        });

        beaconManager.setMonitoringListener(this);
        return beaconManager;
    }

    @Override
    public void onEnteredRegion(Region region, List<Beacon> list) {
        updateUserLocation(region);
    }

    @Override
    public void onExitedRegion(Region region) {
        // Do nothing
    }
}
```

I have verified that the BeaconService is no longer in my apps running in background.

So, since this is not working, I am having a hard time figuring out the issue. Should I declare com.estimote.sdk.BeaconService in my manifest? Should I use my own background Service for handling the monitoring? Or is it maybe recommended to use a foreground Service for handling beacons to make sure the app remains alive, and letting users know that we are monitoring beacons? Also, would this affect the beacon scan period (which currently adjusts to doze nicely)?

On another note: Do I need to do EstimoteSDK.initialize(...) in my Application onCreate method? It's mentioned at the github page, but not at the get started page.

Thanks in advance!

**Comment by magnusgudmandsen** [comment]
I have now verified that this does not work for Nougat either.

But using a Foreground Service to keep the app alive works, and the beacon monitoring still properly adjusts to doze.

So I moved the start/stop monitoring calls to a ForegroundService onCreate/onDestroy to resolve this issue, and simply toggling beacon monitoring by starting/stopping the service.

**Comment by pawelDylag** [comment]
Hello @magnusgudmandsen !

Thanks for reporting that. Android system might kill our beacon service whenever it wants - especially after one/two day constant scan. We can do nothing about it. Your idea with launching service in the foreground is pretty neat - the only downside is that user is constantly aware of this process via notification bar. Not all our developers wan't that behaviour, so we decided to use background service. Let me know how this solution works in the long run!

**Comment by magnusgudmandsen** [comment]
@pawelDylag Wouldn't using START_STICKY as a return value to the Service's onStartCommand solve this issue by letting the Android system know that we want this service to run whenever we can? This should signal to the Android OS that this service should restart again once we have enough memory to run it again (or for whatever reason it was killed).

Also, even if all developers might not want that behaviour, it would be really convenient to allow us to set it to the BeaconManager instead of implementing it ourselves (as many might want this behaviour for continuous scanning).

Such a method could have something like the following signature, demanding that we supply the notification that should be showed:

```
public void startForegroundNotification(@NonNull Notification notification) {
    startForeground(ONGOING_NOTIFICATION_CONSTANT, notification);
}

public void stopForegroundNotification(boolean removeNotification) {
    stopForeground(removeNotification);
}
```

When started, this should allow the beacon monitoring to be run in the background indefinitely, and conform to the demands from Android that the user is aware of this.


My current solution is a very simple background service that just calls my extended BeaconApplication class to do all the dirty work. When the service is created, I start it in foreground with a notification and start monitoring, and when the service is destroyed I stop monitoring (and the notification is automatically removed when service is destroyed). 
The BeaconManager callbacks are handled in the BeaconApplication class, which also contains the BeaconManager. This works since the Application object is always alive while the service is alive.

**Comment by pawelDylag** [comment]
I encourage you to try our new **ProximitySDK** 🚀 - it is dedicated for creating proximity interactions with our beacons - its main focus is to deliver the reliable enter/exit experience according to a different zones of beacons, based on our own data-science, and Estimote Monitoring packet. 
**It works extremely well with Android 5.0-8.0 devices** (full support for Nougat, and Oreo included), and also allows you to configure it to keep scanning in the background.

Here is the official repository page ->  https://github.com/Estimote/Android-Proximity-SDK

Also, we keep posting updates about the progress of our development [**on this thread at our forums**](https://forums.estimote.com/t/estimote-android-sdk-official-progress-reports/7450). 
**I encourage you to track it in order to be super up-to-date** :)

Please, check the mentioned [new SDK](https://github.com/Estimote/Android-Proximity-SDK) - the current SDK will soon be deprecated, and we will support only critical issues for some time.
