### ISSUE TITLE
Where is the SDK source?

### ISSUE THREAD

**Issue by spapas** [Estimote/Android-SDK#191]
I can't find the SDK source anywhere and I have to decompile it to resolve various issues (check also #189, #190). I can only find a binary aar file in the proper location https://github.com/Estimote/Android-SDK/tree/master/EstimoteSDK

Can you please put the source of your SDK where it belongs so that we can download it ?

Also I'm not sure if the MIT license you use is compatible with binary releases (!)

**Comment by edwardhu** [comment]
They don't provide source code.
I've ask before.

**Comment by spapas** [comment]
Then they should:

* Pay a lawyer to create a commercial license and to change it from MIT 
* Remove completely this (non needed) repository
* Provide *better* quality to their tools and documentation

**Comment by pawelDylag** [comment]
Hello @edwardhu , @spapas 

For now our SDK's are not "open-source" - sorry for that. As for our documentation - we are working to add more clarity and improve overall quality, so stay tuned :)
