### ISSUE TITLE
Beacon PublicIdentifier on Android

### ISSUE THREAD

**Issue by campersau** [Estimote/Android-SDK#193]
On iOS there is a [`PublicIdentifier` property](https://github.com/Estimote/iOS-SDK/blob/c0899ceab2ebd219e38e7329daef41b05d17827a/EstimoteSDK/EstimoteSDK.framework/Versions/A/Headers/ESTBeaconVO.h#L23) which refers to the Identifier on cloud.estimote.com

Is there a way to get this information on android too?

**Comment by pawelDylag** [comment]
Hey @campersau 

**ESTBeaconV0** refers to our old cloud API. There is no public identifier field in our `BeaconInfo` class. Instead you can try fetching data from our current api (2.0) through
 ```public void fetchDeviceDetails(DeviceId identifier, CloudCallback<Device> callback)```
**Device** object has all necessary info and public identifier too.

**Comment by campersau** [comment]
Thanks, but this does not work with monitoring / ranging right? Because we only get the `Beacon` object and not the `DeviceId`. So we need an additional `ConfigurableDevicesScanner`?

**Comment by pawelDylag** [comment]
Technically, yes. Our devices are available to advertise many different packets, so the logical binding of `iBeacon identifier<-> Estimote device` is inappropriate.  Basically if you need `deviceId` it means you want to manage your physical device - in that way you need to look for `ConfigurableDevices` nearby, so using `ConfigurableDevicesScanner` is the good idea. If you tell me what use-case you are trying to accomplish, maybe I would help you more :)

**Comment by campersau** [comment]
We are doing monitoring to detect if a user entered a beacon range. Then we need the `PublicIdentifier` to load data from our database which also uses the `PublicIdentifier`.

On iOS this works perfectly because there is a `PublicIdentifier` on the `ESTBeaconVO` class. But not on android.

I think we could also use `proximity + major + minor` as identifier but I was just curious why the apis were different.

**Comment by pawelDylag** [comment]
Okay, so if you are only using iBeacon packets (monitoring is based upon them) to identify our devices, then using smart combination of `proximity + major + minor` will be consistent both for iOS and Android :) 
Good luck with developing and don't hesitate to ask me when you encounter any problem.
