### ISSUE TITLE
Problem startMonitoring (Can't start monitoring)

### ISSUE THREAD

**Issue by phongnx** [Estimote/Android-SDK#195]
Dear, 
I got an issue when use Estimote SDK, Sometime I can't start monitoring.
I had to restart bluetooth and restart Estimote SDK many time and after that I can start monitoring.
This issue occur on Android 5.0 and above.
Please explain for me.
Thank you.

**Comment by pawelDylag** [comment]
Hello @phongnx 
May I see any logs from your case? I need to know, if the issue is caused by our SDK, or maybe some bug on Android level (some phones have problems with filtering BLE devices, so it might be the case).

**Comment by pawelDylag** [comment]
Hello @phongnx 

Any update on this?
