### ISSUE TITLE
estimote SDK will only find beacons from estimote!?

### ISSUE THREAD

**Issue by ashiaka** [Estimote/Android-SDK#20]
Hi,

I just updated the estimote SDK from version 0.2 to 0.3 with the result that my demo app can't find simulated beacons from radiusnetworks MacBeacon simulator anymore. I still can find all beacons from estimote including iOS app and hardware beacons.

I use "new Region("rid", null, null, null)" as region.

Regards,
ashiaka

**Comment by alihaneef** [comment]
Hello. I am just working on both Android and iOS. The very same issue appearing again. I can't detect beacons on Android. Not even in estimote app. But working fine in iOS estimote app.
