### ISSUE TITLE
Unsupported setting TELEMETRY_EN

### ISSUE THREAD

**Issue by mink-lparrouy** [Estimote/Android-SDK#201]
Hello guys,

I try to change the broadcast power of a beacon in my application. I have successfully connect to my device and then I tried to enable telemetry settings in order to change the broadcast power but I have an exception (`com.estimote.sdk.connection.exceptions.UnsupportedSettingException: Unsupported setting TELEMETRY_EN.`).

To enable telemetry settings I follow this readme (https://github.com/Estimote/Android-SDK/blob/master/DOC_telemetry.md).

Thank you

**Comment by pawelDylag** [comment]
Hello @mink-lparrouy !

This kind of exception occurs, when a beacon firmware doesn't support this setting. As far as I know, Telemetry is available since firmware version 4.3.0. Can you verify this for me?

**Comment by mink-lparrouy** [comment]
Yes, you're right my firmware version is 3.2.0.  I bought the first beacon, before proximity beacon, location beacon or stickers. So I can't update this right ?

Thank you

**Comment by pawelDylag** [comment]
Old hardware doesn't support Telemetry settings :(

But don't worry - our newest beacons are so ultra awesome, that you will fall in love with them almost instantly! Check out our beautiful [proximity beacons](http://estimote.com/#get-beacons) and [location beacons](http://estimote.com/#get-beacons) - they are much more powerful now! You can see all the differences and features under the provided links :)

And if you got one, don't forget to leave some feedback about our SDK!
I will be here waiting for you :)
