### ISSUE TITLE
Problem with beacons list in BeaconRangingListener using SDK 1.0.0

### ISSUE THREAD

**Issue by LuckyLuke75** [Estimote/Android-SDK#205]
Hi,

I've updated my build.gradle file to use the new SDK version and I have a problem using the BeaconRangingListener. The beacons list in the callback function is no longer sorted by beacon's proximity but by "detection's date", I've checked using the old SDK version and it does work as intended (i.e when moving beacons around their order in the list change). Is it a bug or is it that the internal logic has changed ? 

Thank you,
Romain.

**Comment by pawelDylag** [comment]
Hello @LuckyLuke75 

It seems like a bug :) Thanks for reporting that! We will add first batch of fixups after switching to 1.0.0 soon. Stay tuned!

**Comment by pawelDylag** [comment]
Fixed in sdk version `1.0.1`

**Comment by LuckyLuke75** [comment]
Thanks for the quick fix :) !
