### ISSUE TITLE
Android 7 not detecting beacons consistently on C#

### ISSUE THREAD

**Issue by OPcody** [Estimote/Android-SDK#215]
I am using StartEddystoneScanning on my android 7 device, to retrieve the beacons Instance, and Namespace, and it picks up beacons, but not consistently like it does on my android 5 device. The BeaconManager.Eddystone event sometimes returns an e.Eddystone.Count of 0.

**Comment by pawelDylag** [comment]
Hello @OPcody 

At first I am a little bit confused about "C#" in your title. Are you using something like Xamarin for our app development? I would also like to know:
1. which phone model are you using (different phone models have different BLE stack and different behaviour, I need to know that)
2. Our SDK version 
3. Your `BeaconManager` settings, like foreground/background scan period
4. TX power and Interval of your Beacons (this strongly affects the discovery of Eddystone packets)

Cheers!

**Comment by OPcody** [comment]
Hello @pawelDylag 

Thank you for answering, but I decided to use something else.
