### ISSUE TITLE
Strange behaviour in ZTE Blade

### ISSUE THREAD

**Issue by loc02998375** [Estimote/Android-SDK#218]
Hi,

I'm currently experiencing a very strange issue on ZTE Blade V7 Plus running Android 6.0. The app only starts to range beacon when the Settings app is opened in Bluetooth page.

Environment:
- Device: ZTE Blade V7 Plus
- Android version: 6.0
- SDK version: 1.0.3
- iBeacon monitor and scan from IntentService in background

Here are the logs:
`I/EstimoteSDK: BeaconManager.disconnect:347 Not disconnecting because was not connected to service
05-15 12:15:21.046 23951-23951/au.com.cabfare.staging I/EstimoteSDK: BeaconService.onCreate:79 Creating beacon service for android version 23
05-15 12:15:21.102 23951-23993/au.com.cabfare.staging V/EstimoteSDK: BeaconService.startMonitoring:195 Starting iBeacon monitoring: BeaconRegion{identifier=cabfare-com-au, proximityUUID=6c454441-1dac-4f69-94e2-eda728e2ac67, major=null, minor=null, secure=false}`

**Comment by ahmedbey** [comment]
I had the same issues with ZTE Blade V7 Lite. Now with SDK 1.0.13 and official Estimote app 2.1.3 stickers are totally undiscoverable. My laptop discovers ZTE perfectly. By the way, all stickers are also discoverable on the laptop as "unknown" devices.
