### ISSUE TITLE
Doc is not updated

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [Estimote/Android-SDK#222]
Dear Estimote Team,

You documentation, http://developer.estimote.com/android/tutorial/part-1-setting-up/, is not updated to the last version. Thus, the classes that are used in your tutorial, do not exist in the newest version. 

Best Regards,

Francesco Saverio Zuppichini

**Comment by pawelDylag** [comment]
Hello @FrancescoSaverioZuppichini 

Thank you very much for pointing this out :) Our Community Team is working hard on refreshing our dev tutorials. All data will be updated soon. For now I encourage you to use `Docs` from this Github page - should be the most recent data available.
