### ISSUE TITLE
Wrong LEVEL_1 BroadcastingPower value?

### ISSUE THREAD

**Issue by plgru** [Estimote/Android-SDK#224]
Trying to set `BroadcastingPower.LEVEL_1` ends up with

`com.estimote.mgmtsdk.common.exceptions.DeviceConfigurationException: {"errors":[{"identifier":"xxx","errors":[{"message":"Estimote Beacons based on nRF52 don\u0027t support -30 dBm Broadcasting Power, use -40 dBm instead.","source":{"path":"settings.advertisers.ibeacon.0.power"},"type":"device.supportedBroadcastingPowerValues"}]}]}`

and power being set to -12 dBm

In Android Estimote configuration app I can see also power setting to -40dBm.
Is `BroadcastingPower` enum safe to use?

**Comment by pawelDylag** [comment]
Hey @plgru 

Some of our beacons are not able to use -30dBm transmit power. You should use LEVEL_2 for your case. We will make this mechanism more bullet-proof, thanks for reporting this anyway :)

Cheers!
