### ISSUE TITLE
Android Nougat beacon not scan when device in doze mode

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-SDK#225]
Am using android nougat version when device is goes in doze mode beacon not scan.

**Comment by pawelDylag** [comment]
Hellp @rajeshkanna777 

Sorry for such long delay. Basically, the Doze mode stops all pending tasks and delays them to be invoked in "maintenance window". This is why scanning for beacons won't work in this mode. Our scanner is able to scan only in short periods of time. We can do nothing about it in our current SDK. But don't worry, we are working on something much more Android-restrictions compatible, so stay tuned :)
