### ISSUE TITLE
estimoteCloud.fetchBeaconDetails 404 exception

### ISSUE THREAD

**Issue by okonon** [Estimote/Android-SDK#226]
@pawelDylag i am getting following error when fetching beacon info from estimote cloud:
EstimoteCloudException: com.estimote.coresdk.common.exception.EstimoteCloudException: 404 Not Found.

when executing following call:
```
EstimoteCloud estimoteCloud = EstimoteCloud.getInstance();
			estimoteCloud.fetchBeaconDetails(b.getMacAddress(), new CloudCallback<BeaconInfo>() {
				@Override
				public void success(BeaconInfo beaconInfo) {
					// Construct JSON object for beacon.
                    Log.i(LOGTAG, "*** fetchBeaconDetails - " + b.getMacAddress());
					try {
						JSONObject json = new JSONObject();
						json.put("major", beaconInfo.major);
						json.put("minor", beaconInfo.minor);
						json.put("rssi", b.getRssi());
						json.put("measuredPower", beaconInfo.settings.broadcastingPower.powerInDbm);
						json.put("proximityUUID", beaconInfo.uuid);
						json.put("proximity", proximity_);
						json.put("distance", distance);
						json.put("name", beaconInfo.name);
						json.put("macAddress", beaconInfo.macAddress);
						jsonArray.put(json);
					}
					catch (JSONException e){
						Log.e("JSONException", e.getMessage());
					}
				}

				@Override
				public void failure(EstimoteCloudException e) {
                    Log.i(LOGTAG, "*(******** EstimoteCloudException: " + e);
				}
			});
```

The beacon is owned under my account. using SDK 1.0.3

**Comment by pawelDylag** [comment]
Hello @okonon 

Did you initialize our sdk with `appId` and `apptoken`?
Also what is your beacon firmware/hardware number?

Cheers!

**Comment by xcastoreo** [comment]
Hi @okonon,

you have to initialize the SDK as said [here](http://estimote.github.io/Android-SDK/JavaDocs/com/estimote/coresdk/common/config/EstimoteSDK.html#initialize-android.content.Context-java.lang.String-java.lang.String-).
It's recommended that you intialize the SDK in the onCreate() method of your application:
```java
void onCreate(Bundle savedInstanceState) {
    [...]
    // appId and appToken are String objects.
    EstimoteSDK.initialize(this, appId, appToken);
    [...]
}
```
You can find or create those logs in the Estimote [cloud](https://cloud.estimote.com).

**Comment by agiratech-gowtham** [comment]
we initialized  the app id and token properly. we have 7 beacons. In that only getting  3 beacons details. remaining 4 beacons gives 404 not found error..How to rectify that..??
