### ISSUE TITLE
Enable/Disable beacon

### ISSUE THREAD

**Issue by ryderz8** [Estimote/Android-SDK#230]
How can I enable/disable the beacon transmission programmatically?

**Comment by xcastoreo** [comment]
Hi @ryderz8,

I'm not sure you can disable the beacon emissions, Estimote explains it [better than me](https://community.estimote.com/hc/en-us/articles/200889987-Where-is-the-Beacon-s-On-Off-Switch-). Maybe you could be interested by the _flip to sleep_ feature, or the _scheduled broadcasting_ one ([here](https://community.estimote.com/hc/en-us/articles/205413787-What-s-conditional-broadcasting-or-how-to-prolong-battery-life-of-beacons-)).

And it would be better to post your question in the [forum](forums.estimote.com), not in the bug tracker.

**Comment by pawelDylag** [comment]
Hello @ryderz8 !

According to what @xcastoreo said, it depends on a type of your Beacon. 
You can enable/disable all packets in cloud or via our sdk. If you want to do it dynamically, use `flip to sleep` feature (thanks once again @xcastoreo for mentioning that)

Also, for such questions, please use our [forum](https://forums.estimote.com/) :)
