### ISSUE TITLE
Estimote Android-SDK (version 1.0.3) not working on Android N devices

### ISSUE THREAD

**Issue by RafaelSermenho** [Estimote/Android-SDK#231]
Dear Estimote support team,

we are starting a project using Android N devices (Samsung Galaxy S7 and Samsung Galaxy S8) and an Estimote developer kit (2 beacons with firmware version 3.2.0 and one beacon with firmware version 2.2.0). Hardware version of these three beacons is D3.4.

Despite all of our efforts on using Monitoring and Ranging features, it seems the above mentioned kit is not working properly with the latest released Estimote Android-SDK (version 1.0.3). For Monitoring feature nothing happens. For Ranging feature it returns an empty list. However, the very same code works well if downgrading the Estimote Android-SDK to version 1.0.1.

I'm initializing the Estimote SDK with this code :
`    EstimoteSDK.initialize(getApplicationContext(), APP-ID, APP-TOKEN);`

I'm setting the monitoring listener and the ranging listener using the code below:

    beaconManager = new BeaconManager(getApplicationContext());
    beaconManager.setForegroundScanPeriod(1000, 1000);
    beaconManager.setMonitoringListener(new BeaconManager.BeaconMonitoringListener() {
        @Override
        public void onEnteredRegion(BeaconRegion beaconRegion, List<Beacon> list) {
            Log.d("myTag", "onEnteredRegion: " + beaconRegion.getIdentifier());
            ...
        }
        
        @Override
        public void onExitedRegion(BeaconRegion beaconRegion) {
            Log.d("myTag", "onExitedRegion: " + beaconRegion.getIdentifier());
            ...
        }
    });
    
    beaconManager.setRangingListener(new BeaconManager.BeaconRangingListener() {
        @Override
        public void onBeaconsDiscovered(BeaconRegion beaconRegion, List<Beacon> list) {
        	if (!list.isEmpty()) {
        	    Beacon nearestBeacon = list.get(0);
        	    ...
            }
        }
    });

I'm starting the monitoring and ranging using the following code:

    beaconManager.startMonitoring(region);
    beaconManager.startRanging(region);
	
Could you please tell me if I am doing something wrong or missing something else ? Or if this is an issue in the latest released SDK (version 1.0.3) ?

This is a very critical issue for us as we are about to buy a large amount of Estimote developer kits and our solution depends on these feautres (Monitoring and Ranging).

Best regards,
Rafael Sermenho Pedroso

**Comment by lopei** [comment]
I confirm this issue. Beacons are not scanned. Nearables work fine though.

**Comment by pawelDylag** [comment]
Hello @RafaelSermenho , @lopei 

I confirm this is an issue on our side. Though it's only happening for old beacons (with hardware <= D3.4) - and it has low priority for us right now. We'll take a deeper look at this problem in an upcoming week and keep you posted about that :)

**Comment by RafaelSermenho** [comment]
Tks @pawelDylag! I'll make some tests and let you know about it! :)

**Comment by lopei** [comment]
@pawelDylag issue not resolved. Beacons still not being monitored on Android N devices in 1.0.9

**Comment by thebluewings** [comment]
@pawelDylag I got this issue on Android 4.4.2 device, too.   And I tried version 1.0.12, it still not resolved.

**Comment by pawelDylag** [comment]
Hey!
I just wanted you to know that we are in the process of moving our SDK for Android to a completely new architecture. We won't be publishing any updates to our old (current _master_) SDK for a while. 

But don't worry - there is an ALPHA version of our FRESH PROXIMITY SDK available now!
It uses a completely new scanning mechanism and will work on new Android versions like a charm (6.0, 7.0, 8.0).
We did a great job with renovating our ecosystem to cut off the old, messy code, full of hacks for Android KitKat an Jellybean. This is why working with `BeaconManager` was so frustrating by the way. 

Plan for the next couple of weeks: 
1. **ProximitySDK beta release** - our own tag-based proximity. Use it to achieve the same behaviour as using iBeacon (monitoring/ranging). It is uses our own packets called Estimote Location and is backed-up by our own data-science. Read more here -> http://blog.estimote.com/post/166007374930/the-most-reliable-proximity-tech-now-with-a
2. **ScanningSDK beta release** - a separate core library dedicated for raw scanning - it will handle the scanning on all android versions for you, battery efficiency, background/foreground, and will deliver raw stream of packet data (Such as iBeacon, Eddystone, EstimoteLocation, EstimoteTelemetry, etc). 

I encourage you to try it out - there is a ready made app for you to show the possibilities of our completely new SDK -> https://github.com/Estimote/Android-SDK/tree/proximity-sdk
Let us know what you think!
I will keep you updated about the progress.

**Comment by toxicosmos** [comment]
Does it work with nearables?

I have tried it but it doesn't work with my nearable (Mint "door").
If it suppose to work with nearable , maybe I forgot to configure something... I set the app ID and the app token and Run the app sample

**Comment by pawelDylag** [comment]
Hey @toxicosmos 

Unfortunately it's not compatible with Nearables for now. The ProximitySDK uses EstimoteMonitoring protocol packet which can only be advertised by our EstimoteProximity/EstimoteLocation beacons. 
We will consider supporting Nearable protocol also, but to be honest, not in the close future. 

You can still

**Comment by toxicosmos** [comment]
Thank you very much Pawel.

I have a problem then. I'm trying to use Nearables, but it doesn't work with my phones with Android 6 and 7....
It's not working using your "classic" SDK neither this alpha version...
Am I missing anything interesting to try? I've searched in your web tutorials, your forums, and github...

We are thinking about buying new nearables, would it be useful? (The "old" ones were bought in May.)

Maybe we have to wait for the new SDK to be stable and nearable supporting?


Thank you again!

**Comment by pawelDylag** [comment]
@toxicosmos well, we are still discussing where to put the support for Nearables. I cannot promise you that it will be put into ProximitySDK. We try to follow "single responsibility rule", so ProximitySDK should be only responsible for delivering proximity-based experience. But maybe we will add Nearable packet to also allow such experience using nearables. 

Could you tell me what is your use-case? Are you trying to only get user's proximity from nearable? Or are you trying to access sensor data from them? I got a couple of ideas for you.

**Comment by toxicosmos** [comment]
I'm trying only to get user's proximity to my nearable.

I tried this: http://developer.estimote.com/proximity/android-tutorial/
After that , I tried this:  https://github.com/Estimote/Android-SDK/blob/master/Docs/DOC_monitoring_scanning.md#nearable
And ay of them worked, so I've tried this alpha-SDK. 

I'm all ears

**Comment by pawelDylag** [comment]
Hey @toxicosmos - sorry for the delay, I got tons of work recently :)

The new ProximitySDK is totally focused on delivering most reliable proximity experience. This can only be achieved with mixing amazing data-science, with custom hardware+software. Unfortunately, current Nearables are not capable of delivering the necessary minimum to make our ProximitySDK experience as promised. You may, of course, do a simple RSSI measurement on every received BLE packet, but it doesn't work cool and reliable. So we must keep the necessary minimum. 

There are plans of upgrading our Nearables to be able of broadcasting our EstimoteMonitoring protocol, but honestly, it's not in our current quarterly scope. 

You can still play with your Nearables using our current (master branch) SDK :)

Cheers!

**Comment by toxicosmos** [comment]
Thank you very much Pawel!
But your answer gets me to the starting point: I was trying to implement it using the current SDK and couldn't discover/connect to my nearables on Android 6 and 7. (See this: [https://forums.estimote.com/t/estimote-app-is-not-connecting/7470](url) )

**Comment by wafel82** [comment]
Hey @toxicosmos - once again sorry for delayed response, We're currently super-focused on making our new sdk-stack to be production ready.

Just like @pawelDylag  mentioned - Our new ProximitySDK is focused on delivering most reliable proximity experience and Nearables (in current form) are not capable to fulfill  ProximitySDK requirements - they simply does not support all necessary data the ProximotySDK needs to have to operate.

However - you can still use our lower-level scanner implementation to discover Nearables nearby and to perform your specific action based on scanned data. Here's how it can be handled (in Kotlin):

- add proximitySDK dependency to your build.gradle: 
`compile 'com.estimote:proximity-sdk:0.1.0-alpha.5'`

- create instance of our bluetooth scanner: 
```java
bluetoothScanner = EstimoteBluetoothScannerFactory(applicationContext).createSimpleScanner()
```
- start Nearables scan:
```java
 nearableScanHandler =
                bluetoothScanner
                        .estimoteNearableScan()
                        .withOnPacketFoundAction { Log.d("NEARABLE", "Got NEARABLE packet: $it") }
                        .withOnScanErrorAction { Log.e("NEARABLE", "NEARABLE scan failed: $it") }
                        .start()
```
- to stop active scanning use created `nearableScanHandler`:
```java
nearableScanHandler.stop()
```

When scan is active - each time Nearable packet gets discovered then acton passed as `withOnPacketFoundAction` argument will be called
Data passed as an argument to withOnPacketFoundAction lambda is the scanned Nearables packet. You can build your custom logic based on received packet data (like rssi) 
Note that builder used to configure and launch scan offers some additional configuration options (e.g. power consumptions mode) - feel free to explore them :)

Hope this will address you needs 

Regards
Wojtek

**Comment by agiratech-sankar** [comment]
Hi 
 I have tried to find the nearest beacon, few mobiles this app working fine but latest Android OS it's not finding the beacon. I used this SDK  - implementation 'com.estimote:sdk:1.4.5'.

 beaconManager.setRangingListener((BeaconManager.BeaconRangingListener) (region, list) -> {
            Log.d("BeaconService", "" + list.size());

          
        });

Anything I Missed, pls share any idea.
