### ISSUE TITLE
Screen flickering when denying permissions

### ISSUE THREAD

**Issue by allbiin** [Estimote/Android-SDK#232]
We are calling `SystemRequirementsChecker.checkWithDefaultDialogs()` from _`onResume()`_ to check for permissions, as documentation suggests. When a user denies the permission, the screen flickering. 

Here is what is happening:
1. User start activity
2. User gets asked for permission in a new transparent activity (according to documentation)
3. User denies the permissions and is directed back to previous activity (onResume() is called again), a message is shown that permissions are needed
4. User gets asked for permissions agains since the onResume() is called 
5. User denies the permission with checking the "Don't ask me again" box
6. User is directed back to the previous activity -> onResume()
7. onResume() tries to check permissions, can't do that, dark background of the "transparent" activity comes up, goes back to the previous activity, a message is shown that app requires certain permission
8. In milliseconds, onResume() has been called again, the app tries to check permissions and the whole thing starts again

So what you have is endless loop/recursion and since the "transparent" activity is starting constantly, the flickering occurs.
 
Android 7
Samsung Galaxy S7
Estimote SDK 1.0.3

**Comment by pawelDylag** [comment]
Hello @allbiin 

This is related to: #155
All in all, if you want your dialog to be restartable, you need to implement your own functionality.
The default implementation is designed to provide only one check in your activity `onCreate()`

Have a nice day!

**Comment by allbiin** [comment]
Hi again!

I believe you misunderstood the issue. We do not want to re-open the dialog. The problem is that if a user denies the permissions for location and checks the "Don't ask me again"-box when asked again, the screen start flickering and makes the application unusable. We want to report this as it is a serious issue.

**Comment by mr-goldhands** [comment]
I confirm and vote this bug.
It not duplicate #155 . It is other.
You can reproduce behavior described by @allbiin even in your "Notification" example.

**Comment by mr-goldhands** [comment]
Even if you call `SystemRequirementsChecker.checkWithDefaultDialogs()` from `onCreate()` but
"Don't keep activities" in "Developer Settings" is turned ON this bug will reveal.
Method `onCreate()` will be invoked every time after calling `SystemRequirementsChecker.checkWithDefaultDialogs()` every time and app will be flickering.
