### ISSUE TITLE
Estimote Android-SDK (version 1.0.3)  Beacon not scanning

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-SDK#233]
Am using android one OnePlus 3T 7.1.1 
Bacon version
Firmware Version  4.9.4
Hardware Version  G1.8

My code
 private static final BeaconRegion ALL_ESTIMOTE_BEACONS_REGION = new BeaconRegion("rid", null, null, null);

     beaconManager.startRanging(ALL_ESTIMOTE_BEACONS_REGION);
   @Override
    public void onBeaconsDiscovered(BeaconRegion beaconRegion, List<Beacon> beacons) {
        beaconList = beacons;}

After 3 min the beacon list is Zero ,Beacon not scanning.

**Comment by lopei** [comment]
I confirm this issue. Beacons are not scanned. Nearables work fine though.

**Comment by rajeshkanna777** [comment]
am using estimote app it showing all beacon and i go to switch off and switch on the bluetooth  its not scanning (not showing the beacon) in estimote app and Estimote Android-SDK (version 1.0.3)  also.

**Comment by pawelDylag** [comment]
Hey! 

We have released version `1.0.9` with slightly changed scanning mechanism on Nougat devices. Please confirm this issue still occurs :)

**Comment by rajeshkanna777** [comment]
Am using this permission and code
 <uses-permission android:name="android.permission.REQUEST_IGNORE_BATTERY_OPTIMIZATIONS" />

 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            String packageName = getPackageName();
            PowerManager pm = (PowerManager) getSystemService(Context.POWER_SERVICE);
            if (!pm.isIgnoringBatteryOptimizations(packageName)) {
                Intent intent = new Intent();
                intent.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
                intent.setData(Uri.parse("package:" + packageName));
                startActivity(intent);
            }
        } after 30 min beaconRegion stoped and beacon list size is zero.

**Comment by rajeshkanna777** [comment]
i just went to some other place so that place no beacon after few min i came back to beacon place , 
 that time beacon not scanned show only  mac address only

07-21 18:08:19.029 8759-8854/? E/bt-btm: new address: ea:54:2a:58:aa:31
07-21 18:08:19.033 8759-8854/? E/bt-btm: new address: 18:65:90:d5:24:ee
07-21 18:08:19.080 8759-8854/? E/bt-btm: new address: f0:e2:d8:a0:75:81
07-21 18:08:20.010 8759-8854/? E/bt-btm: new address: 4c:8e:3a:6a:2f:0d
