### ISSUE TITLE
Does nearable have an android SDk? because according to the nearables app given on the estimote website it only supports ios platform.If yes please help with how to start with it

### ISSUE THREAD

**Issue by divitavora** [Estimote/Android-SDK#241]

**Comment by pawelDylag** [comment]
Hello @divitavora 

This page is dedicated to issue/bug reporting. If you have any questions about the product itself, feel free to post it on our forums here -> https://forums.estimote.com/ 

As for me - Nearables are supported in our SDK and you can scan for them just as you do for normal iBeacon packets. Please remember that if you want to connect to a nearable, you should be shaking it - only then it is able to connect to.
