### ISSUE TITLE
Estimote sdk version 1.0.10 asking allowBackup value=true but i want  allowBackup value=(false) 

### ISSUE THREAD

**Issue by rajeshkanna777** [Estimote/Android-SDK#245]
Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@allowBackup value=(false) from AndroidManifest.xml:26:9-36
  	is also present at [com.estimote:sdk:1.0.10] AndroidManifest.xml:12:9-35 value=(true).
  	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:24:5-93:19 to override.

**Comment by Sharprender** [comment]
I have the same issue with 1.0.12

**Comment by wafel82** [comment]
Hi, 
We'll try to adjust this stuff in upcoming SDK version. So - stay tuned :)

Regards
Wojtek

**Comment by wafel82** [comment]
Hi,
We just released new SDK version. We've done some Manifest and resources cleanup as a part of this release. Check it out and let us know if it addresses this issue :)

Regards
Wojtek

**Comment by Sharprender** [comment]
with 1.0.13 version this bug is fixed.
No need for 

`tools:replace="android:allowBackup"`

**Comment by wafel82** [comment]
Good to hear :)
I'm closing  the topic then

Regards
Wojtek
