### ISSUE TITLE
Migrating from 0.16.0 to 1.0.12

### ISSUE THREAD

**Issue by Sharprender** [Estimote/Android-SDK#247]
I'm migratiiong from 0.16.0to 1.0.12
My problem is, that I can't find the old function Utils.restartBluetooth() anymore.
Is this function still available or completely removed?

**Comment by wafel82** [comment]
Hi, 
True - there are some breaking changes between pre 1.X  releases and the current versions(1.x and above). One of those changes is Utils removal :/.
It's no longer available as a part of the Estimote SDK.
