### ISSUE TITLE
Ranging Beacons - Updates every 5 minutes (Android 4.3)

### ISSUE THREAD

**Issue by giannisdoukas** [Estimote/Android-SDK#253]
Hello. I have a very simple app which ranges the beacons with their distance. I have tested on some devices (Android 6) and it works correctly but on a Xiaomi Redmi 1S with Android 4.3 the function onBeaconsDiscovered (and onEddystonesFound I have tested both) it is called every 5 minutes. I have tried to change the period and the sleep time with the setForegroundScanPeriod but it makes no difference. 

I have tested it with sdk 1.1.0 and 1.0.15.

Tested also:
Lenovo A7000        Android 6.0     - OK
Xiaomi Redmi 4A   Android 6.0.1   - OK
Xiaomi Note 3 Pro Android 6.0.1   - OK
Samsung Galaxy J5 Android 6.0.1  - OK

Feel free to ask any additional information.

Thank you in advance

**Comment by giannisdoukas** [comment]
Same behavior with sdk 1.2.0.

**Comment by pawelDylag** [comment]
Hey!
I just wanted you to know that we are in the process of moving our SDK for Android to a completely new architecture. We won't be publishing any updates to our old (current _master_) SDK for a while. 

But don't worry - there is an ALPHA version of our FRESH PROXIMITY SDK available now!
It uses a completely new scanning mechanism and will work on new Android versions like a charm (6.0, 7.0, 8.0).
We did a great job with renovating our ecosystem to cut off the old, messy code, full of hacks for Android KitKat an Jellybean. This is why working with `BeaconManager` was so frustrating by the way. 

Plan for the next couple of weeks: 
1. **ProximitySDK beta release** - our own tag-based proximity. Use it to achieve the same behaviour as using iBeacon (monitoring/ranging). It is uses our own packets called Estimote Location and is backed-up by our own data-science. Read more here -> http://blog.estimote.com/post/166007374930/the-most-reliable-proximity-tech-now-with-a
2. **ScanningSDK beta release** - a separate core library dedicated for raw scanning - it will handle the scanning on all android versions for you, battery efficiency, background/foreground, and will deliver raw stream of packet data (Such as iBeacon, Eddystone, EstimoteLocation, EstimoteTelemetry, etc). 

I encourage you to try it out - there is a ready made app for you to show the possibilities of our completely new SDK -> https://github.com/Estimote/Android-SDK/tree/proximity-sdk
Let us know what you think!
I will keep you updated about the progress.
