### ISSUE TITLE
can't stop ranging/monitoring in android 6,7 on Bluetooth turning off 

### ISSUE THREAD

**Issue by MrRoot313** [Estimote/Android-SDK#254]
Hi,
i'm trying to stop ranging and monitoring to improve battery performance but it can't working, it giving me these logs,
i can't understand what's going in, 
need help, thanks

09-26 14:40:55.853 13229-13229/... I/EstimoteSDK: BeaconManager.stopRanging:694 Not stopping ranging, not connected to service
09-26 14:40:55.853 13229-13229/seronic.telenor I/EstimoteSDK: BeaconManager.stopRanging:694 Not stopping ranging, not connected to service
09-26 14:40:55.853 13229-13229/.. I/EstimoteSDK: BeaconManager.stopRanging:694 Not stopping ranging, not connected to service
09-26 14:40:55.853 13229-13229/... I/EstimoteSDK: BeaconManager.stopRanging:694 Not stopping ranging, not connected to service
09-26 14:40:55.853 13229-13229/... I/EstimoteSDK: BeaconManager.stopRanging:694 Not stopping ranging, not connected to service
09-26 14:40:55.853 13229-13229/..... I/EstimoteSDK: BeaconManager.stopRanging:694 Not stopping ranging, not connected to service
09-26 14:40:55.853 13229-13229/...I/EstimoteSDK: BeaconManager.stopMonitoring:941 Not stopping monitoring, not connected to service
09-26 14:40:55.853 13229-13229/.... I/EstimoteSDK: BeaconManager.stopMonitoring:941 Not stopping monitoring, not connected to service
09-26 14:40:55.853 13229-13229/.... I/EstimoteSDK: BeaconManager.stopMonitoring:941 Not stopping monitoring, not connected to service
09-26 14:40:55.863 13229-13229/... I/EstimoteSDK: BeaconManager.stopMonitoring:941 Not stopping monitoring, not connected to service
09-26 14:40:55.863 13229-13229/.....I/EstimoteSDK: BeaconManager.stopMonitoring:941 Not stopping monitoring, not connected to service
09-26 14:40:55.863 13229-13229/... I/EstimoteSDK: BeaconManager.stopMonitoring:941 Not stopping monitoring, not connected to service
09-26 14:40:55.863 13229-13229/... I/Bluetooth: Bluethoot Turned Off.........

**Comment by pawelDylag** [comment]
Hey!
I just wanted you to know that we are in the process of moving our SDK for Android to a completely new architecture. We won't be publishing any updates to our old (current _master_) SDK for a while. 

But don't worry - there is an ALPHA version of our FRESH PROXIMITY SDK available now!
It uses a completely new scanning mechanism and will work on new Android versions like a charm (6.0, 7.0, 8.0).
We did a great job with renovating our ecosystem to cut off the old, messy code, full of hacks for Android KitKat an Jellybean. This is why working with `BeaconManager` was so frustrating by the way. 

Plan for the next couple of weeks: 
1. **ProximitySDK beta release** - our own tag-based proximity. Use it to achieve the same behaviour as using iBeacon (monitoring/ranging). It is uses our own packets called Estimote Location and is backed-up by our own data-science. Read more here -> http://blog.estimote.com/post/166007374930/the-most-reliable-proximity-tech-now-with-a
2. **ScanningSDK beta release** - a separate core library dedicated for raw scanning - it will handle the scanning on all android versions for you, battery efficiency, background/foreground, and will deliver raw stream of packet data (Such as iBeacon, Eddystone, EstimoteLocation, EstimoteTelemetry, etc). 

I encourage you to try it out - there is a ready made app for you to show the possibilities of our completely new SDK -> https://github.com/Estimote/Android-SDK/tree/proximity-sdk
Let us know what you think!
I will keep you updated about the progress.
