### ISSUE TITLE
BulkUpdater is setting certain fields to default value

### ISSUE THREAD

**Issue by joharei** [Estimote/Android-SDK#258]
When using the BulkUpdater, some fields seem to be set to a default value instead of the expected value.

We are specifically trying to change advertising interval and broadcasting signal from the Estimote Cloud. When we run our app that implements BulkUpdater, the beacons with pending updates seem to be updated. But no matter what values we are trying to set, advertising interval is always changed to 512 ms, and broadcasting power to -4 dBm.

**Comment by wafel82** [comment]
Hi @joharei 
I apologize for super-delayed response. We are currently super focused on our new SDKs stack implementation. We are building our new stack from scratch and we strongly believe our new SDKs set will be much more reliable, stable and first of all -free from the issues like the one you submitted :).

I've tried to reproduce the issue you described. I've used our official SDK in newest version (1.4.0). I've tried it on two phones - Google Pixel XL running Android 8.1 and Google Nexus 6P running Android 8.0
Result - no luck; everything work as expected :)

To dig it deeper - could you provide some more details about your setup?
It would be helpful for us to get the following data:
 - SDK version you are using;
 - Phone Model you are using;
 - Android version you are observing issue on;
 - type of beacon you are trying to synchronize ({roximity/Location/UWB);
 - Beacons' firmware version;

Regards
Wojtek
