### ISSUE TITLE
thread exiting with uncaught exception, FATAL EXCEPTION: BeaconServiceThread

### ISSUE THREAD

**Issue by MrRoot313** [Estimote/Android-SDK#260]
hi i'm facing this type of Exception in my app,, is this bug or ma doing something wrong>>??
attached screenshots of my logs
thanks
![error](https://user-images.githubusercontent.com/7576888/31165217-a8ad1324-a903-11e7-9494-aa5427f7cf1a.PNG)

**Comment by ali991** [comment]
Yes, me too i also had a lot of crashes of this in my Crashlytics dashboard.

**Comment by ali991** [comment]
If you call this method : beaconManager.setBackgroundScanPeriods(scanTime, waitTime) it will trigger this exception

**Comment by pawelDylag** [comment]
http://blog.estimote.com/post/166007374930/the-most-reliable-proximity-tech-now-with-a

**Comment by abiela** [comment]
Duplicated issue -> https://github.com/Estimote/Android-SDK/issues/263
