### ISSUE TITLE
the tutorial example it's not work

### ISSUE THREAD

**Issue by ChristianMartinezSDK** [Estimote/Android-SDK#265]
Hello guys ! i tried to learn about my beacons and i follow the example :http://developer.estimote.com/proximity/android-tutorial/
its show the msg " helloWorld It has stopped"
not work :( 
what problem could be?
teoricly it's all ok (Permission and sdk)
i have android 6.0.1,

**Comment by Poberro** [comment]
If you could send us a stack trace and your code it would enable us to find possible cause of the problem, since message "YourApp has stopped" can be caused by many exceptions (like for example NullPointerException from uninitialised variables).
