### ISSUE TITLE
ConfigurableDevice accuracy

### ISSUE THREAD

**Issue by Sharprender** [Estimote/Android-SDK#266]
Hi,

in SDK 0.16.0 there was a ConfigurableDeviceScanner and it was possible to computeAccuracy or computeProximity from "ConfigurableDevicesScanner.ScanResultItem".

Now in 1.4.0 there is no ConfigurableDeviceScanner and we have  to use ConfigurableDeviceListener from BeaconManager.

1. There is no possibility to computeAccuracy/ Proximity from ConfigurableDevice.
If I use computeAccuracy(rssi, txPower), then I get huge values like: rssi = -59; txPower = -12; computeAccuracy = 197477.82765227437

Is there a possibility to get the accuracy and proximity from ConfigurableDevice?

2. In 0.16.0 in ConfigurableDeviceScanner, it was possible to filter the devices with "setOwnDevicesFiltering(true);"

How can I do it in 1.4.0?

**Comment by Poberro** [comment]
Please do not do this. Some of the devices do not advertise measured power and it won't be possible to calculate accuracy (that is why you are getting huge numbers. 
ConfigurableDevice is intended to be used to configure device, not to provide proximity/location. 
See discussion:
https://forums.estimote.com/t/configurabledeviceslistener-question/7550
