### ISSUE TITLE
Unable to detect some of my Nearable stickers

### ISSUE THREAD

**Issue by yushakareem** [Estimote/Android-SDK#275]
## Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * My Android device/devices supports BLE and has Android OS version >= 4.4 
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version:** [1.4.1]

**Android devices affected:** [Google Pixel 2 XL]

**Android OS version affected:** [8.1.0]

**Nearable hardware version:** [SB0] 

## Description

I have 10 Nearable stickers. But I am only able to detect 5. 
I have checked for their detection using the original Android Estimote App and the quick-start-code provided here (https://github.com/Estimote/Android-SDK/blob/master/Docs/quick_snippets.md).

Hence, the question is: Perhaps they came to me with dead batteries? How do I know for sure?

The stickers that are **detectable**:
Door, Chair, Bike, Bed, Dog

The stickers that are **not detectable**: 
Fridge, Shoes, Car, Bag, Ice

Note that, for the stickers that are not detectable:
I have tried nudging them and shaking them ( to wake them up :D )
I have checked their settings in the estimote-cloud. The settings are the same as for the stickers that are detectable.

Any tips or suggestions, most welcome :)

Thank you
Kind regards
Yusha

**Comment by wafel82** [comment]
Hi @yushakareem 
Thanks for reporting this. Have you tried to detect your stickers with [Estimote's app](https://play.google.com/store/apps/details?id=com.estimote.apps.main) ?

Also - check out our new Proximity-SDK goodness 🚀. 
You can simply include it in your build.gradle with `compile 'com.estimote:proximity-sdk:0.2.0'` and scan for Stickers as follows:
```kotlin
    EstimoteBluetoothScannerFactory(applicationContext)
        .getSimpleScanner()
        .estimoteNearableScan()
        .withOnPacketFoundAction { Log.d("NEARABLE", "Got NEARABLE packet: $it") }
        .withOnScanErrorAction { Log.e("NEARABLE", "NEARABLE scan failed: $it") }
        .start()
```
Let us know if [Estimote's app](https://play.google.com/store/apps/details?id=com.estimote.apps.main) and/or Proximity-SDK's scanner is able to detect all your stickers.

Regards
Wojtek

**Comment by yushakareem** [comment]
Hi @wafel82 !

Thank you for the prompt reply :)
I tried to detect with the Estimote App and the proximity-sdk:0.2.0.
Still the same result. Only able to detect those 5 stickers (Door, Chair, Bike, Bed, Dog). 

Perhaps they arrived with dead batteries, maybe?

**Comment by wafel82** [comment]
Hi @yushakareem 
Since 5 from your stickers can be successfully detected - It is not phone-hardware/Android/SDK issue. It looks like something is with stickers you are not able to detect.
How old those stickers are (How long are you playing with them)?

Regards
Wojtek

**Comment by yushakareem** [comment]
We got them in December. Started playing with them since January, after Christmas :) 

What do you think, might be the issue?

Kind regards,
Yusha

**Comment by yushakareem** [comment]
Hi! @wafel82,

Just a very **quick question**: 
In proximity-sdk: Currently, are there functions available (Like they are for the beacons) for 'monitoring','ranging' and 'triggering', using the nearable-stickers?

If yes, please, could you give some examples :) 

Thank you!
Yusha

**Comment by Poberro** [comment]
It looks like hardware issue (dead battery, damaged circuit board, etc.) Not an SDK issue. Closing.
