### ISSUE TITLE
Use Bluetooth only (without GPS)

### ISSUE THREAD

**Issue by burnix** [Estimote/Android-SDK#276]
I have bluetooth enabled, location permissions granted but GPS disabled. I receive such error log `On Android M and above detecting beacons requires Location to be turned on` but still can use your SDK for my needs. I don't need exact proximity either as I want to stay with GPS turned off. Can I ignore with caution?

**Comment by Poberro** [comment]
Yes. It needs permission ACCESS_COARSE_LOCATION to start BLE scanning. This permissions  does not require GPS.
