### ISSUE TITLE
Scanning for configurable devices takes a lot of time

### ISSUE THREAD

**Issue by wrightX** [Estimote/Android-SDK#278]
Hello,
I am trying to connect to beacon and change its gpios. But when I am scanning to find my configurable device I can connect to it's taking a lot of time and often doesn't find it at all. Is it some way to make it work better? It is working great when I shake my beacon but eventually it will be placed stationary and I wouldn't be able to do that.

**Comment by wrightX** [comment]
Thank you for your answer. 
Can I somehow change connectivity settings from your android app? I can't see option to do it there

**Comment by Poberro** [comment]
It is not supported right now, but it you change that setting in Cloud, it will be synchronised when you connect to the beacon.
