### ISSUE TITLE
Unable to attach Nearables in IndoorLocationView

### ISSUE THREAD

**Issue by ankushpatel18** [Estimote/Android-SDK#280]
## Prerequisites

* [ X] Put an X between the brackets on this line if you have done all of the following:
    * My Android device/devices supports BLE and has Android OS version >= 4.4 
    * My Android device/devices have Bluetooth enabled
    * My app has Location Permissions granted
    
## Basic information

**Estimote SDK version: [ (1.4.1)]

**Android devices affected:** [LG Nexus 5X, Samsung s7 EDGE, Samsung S5, Moto g]

**Android OS version affected:** [ 'Oreo 8.0.0', 'nougat 7.0', 'Marshmallow 6.0')]

**Beacon hardware version:** [SB0.] 

## Description

[I am unable to show Nearables in IndoorLocationView. I am going to develop something that will look much similar to your sample video that is [https://youtu.be/9cH44pE1Fks]]
I have already implemented indoor SDK and estimote SDK to show user's movements now i need to show nearables that i receive using nearable listener in indoorLocation view with sticker images.

**(Optional) Steps to reproduce:**

1. [Add Estimote SDK and indoor SDK]
2. [Add a Location using UWB beacons]
3. [Add listenres for onPositionUpdate and nearableListener]
4. [Now i'm unable to show received Nearables in indoorLocationView]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [It shows only some squares for each sticker using "indoorLocationView.setCustomPoints" i want to show something like showing in video.]

![location](https://user-images.githubusercontent.com/13097753/37592487-cff37b9e-2b94-11e8-90ff-26a93629eebd.png)

```

**Comment by Poberro** [comment]
This issue is about IndoorSDK. Please reopen it on Indoor SDK:
https://github.com/Estimote/Android-Indoor-SDK
