### ISSUE TITLE
Is Android-SDK supported for Amazon Fire OS?

### ISSUE THREAD

**Issue by ajitgaur** [Estimote/Android-SDK#281]
## Description

Before starting using Android SDK for an app on Amazon's Fire, just wanted to ask if Estimote SDK has any known restrictions for Amazon Fire OS?

Is there any custom change needed if that is not the case?

**(Optional) Steps to reproduce:**

**Comment by Poberro** [comment]
I don't know about any restrictions but it was never officially tested on Fire OS.

**Comment by ajitgaur** [comment]
Thanks Poberro,
