### ISSUE TITLE
How to mute BluetoothAdapter logs?

### ISSUE THREAD

**Issue by mohitb117** [Estimote/Android-SDK#35]
Is there any way to silence the debug Logs of the scans Bluetooth Adapter , 

I dont want to see the Scan Results while Generating Logs! 

03-24 20:18:31.024  17852-18223/net.fluidstream.radiovicenza D/BluetoothAdapter﹕ onScanResult() - Device=F9:57:DA:5A:67:09 RSSI=-66

03-24 20:18:31.594  17852-17990/net.fluidstream.radiovicenza D/BluetoothAdapter﹕ stopLeScan()

03-24 20:18:31.634  17852-17990/net.fluidstream.radiovicenza D/BluetoothAdapter﹕ startLeScan(): null

03-24 20:18:31.634  17852-17864/net.fluidstream.radiovicenza D/BluetoothAdapter﹕ onClientRegistered() - status=0 clientIf=5

I don't want more logging noise... I am doing my own logging and this is just interference! 

I know i can filter the BluetoothAdapter ones out... but i dont want to unless there already exist a switch in the SDK or are they a part of the Bluetooth Stack??

**Comment by stephan-henningsen** [comment]
Bump =)  I'm getting tired of these log entries too.

**Comment by elenzil** [comment]
is there a possibility these log lines have a performance impact ?
I'm seeing about 24 per second for onScanResult.

**Comment by stevensanborn** [comment]
I have been using:
^(?!BluetoothAdapter)(?!BluetoothLeScanner) in the regex filter for tag

**Comment by sakkeerhussain** [comment]
It can be archived by adding ^(?!.*(BluetoothAdapter)).*$  this value to 'by Log Tag' field of Log cat filter message settings
I know this not the exact solution but it worked for me !

**Comment by stephan-henningsen** [comment]
Yeah, I just discovered this the day before @stevensanborn posted!

In Eclipse LogCat I made a new Filter:

Filter Name: MyApp excluding BT
by Log Tag: ^(?!.*(BluetoothAdapter|BluetoothLeScanner)).*$
by Application Name: com.example.myapp

But still it would be preferable to have Google make their system services stfu.

**Comment by rharter-phunware** [comment]
I've filed a bug in Android for this issue.  It appears as though a debug flag was left true in production.  Please star the issue in the Android bug tracker (don't comment unless you have something constructive to add, the star is your vote).

**Comment by pawelDylag** [comment]
Clearing old stuff
