### ISSUE TITLE
make the sdk available in maven central

### ISSUE THREAD

**Issue by francisdb** [Estimote/Android-SDK#43]
Modern builds fetch dependencies from a central repo instead of adding jars to the lib folder.

More info on deploying to central here:
http://central.sonatype.org/pages/ossrh-guide.html

**Comment by amouly** [comment]
+1

**Comment by sumitsahoo** [comment]
Yup. Really needed for Gradle build.

**Comment by gordokyl** [comment]
+1

**Comment by giluna** [comment]
+1

**Comment by nelkenheinrich** [comment]
+1

**Comment by Kyrremann** [comment]
Maven og JCenter please :)

**Comment by yesidlazaro** [comment]
+1

**Comment by Marabita** [comment]
for community, this is very important to be done...

**Comment by francisdb** [comment]
If it's not on maven central it does not exist! It's as simple as that.

**Comment by wiktor** [comment]
We cannot publish library either on Maven Central or jCenter as this is not open source library.




We need to investigate private maven repository.

**Comment by Kyrremann** [comment]
Ah, yes, that is true. Are there some specific reason for this not being open source? I haven't used much time on these BLE libraries, but aren't they mostly doing the same?

**Comment by wiktor** [comment]
Our beacon configuration is our IP.

**Comment by Kyrremann** [comment]
Forgot to answer this. I understand that it's your IP, and you are free to use it as you please. But that doesn't really answer why it can't be open sourced. And I'm not necessarily talking about [free software](https://www.gnu.org/philosophy/open-source-misses-the-point.html), but open so we can see what is done, and help Estimote expand on it.

**Comment by amouly** [comment]
@Kyrremann +1

**Comment by wiktor** [comment]
We are not open sourcing it as for now we do not want to reveal how we connect and configure our beacons.

**Comment by Kyrremann** [comment]
Okay, that is understandable :)
Anyway, I think https://bintray.com/ allows for non OSS, it's just free if it's OSS.

**Comment by jitpack-io** [comment]
Btw, we'll be adding private repo support to [JitPack](https://jitpack.io) so you'd be able to easily publish closed-source libraries as maven artifacts. If that sounds interesting happy to notify you when its available

**Comment by wiktor** [comment]
@jitpack-io Yes, please please do, :).

**Comment by wiktor** [comment]
There is progress. From [version 0.5](https://github.com/Estimote/Android-SDK/releases/tag/0.5) SDK is distributed as AAR.

**Comment by Kyrremann** [comment]
cheers!

**Comment by amouly** [comment]
Awesome!!!

**Comment by AndrewJack** [comment]
+1

**Comment by Den-Rimus** [comment]
Please add this to documentation about aar-distributed library:
http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger#TOC-tools:overrideLibrary-marker

In case if your app uses minSdk lower that estimote's - the is needed to build successfully.
For me it worked even without specifying minSdk in Manifest (since it is present in my build.gradle file already) - just this line is enough: `<uses-sdk tools:overrideLibrary="com.estimote.sdk" />`

**Comment by wiktor** [comment]
@Den-Rimus Thanks a lot, appreciated. Added to README.

**Comment by jitpack-io** [comment]
@wiktor Got an update. JitPack now supports publishing a library that's built from a private repository. The library can be made public while the source code remains private.

**Comment by erawhctim** [comment]
@wiktor Any update on publishing this library via JitPack now that the feature is supported?

**Comment by wiktor** [comment]
Good news. We have green light from Maven Central to be included in them.

Starting from version 0.8.7, Estimote SDK is available in Maven Central: `com.estimote:sdk:0.8.7@aar`.
