### ISSUE TITLE
Nexus 4 ranging in service + wifi

### ISSUE THREAD

**Issue by jbruchanov** [Estimote/Android-SDK#46]
I put the code example into a service.
It works fine, but in the time of Ranging it seems that wifi is "blocked" and i'm not able to use it. (net requests failing for time out). 

Any ideas what can be wrong or N4 has some "share" hw implementation for BT+WIFI ?

**Comment by victorraft** [comment]
This seems to happen in all the Nexus devices, the Samsung Galaxy S4 mini and a lot of Motorola. 
How do you guys are dealing with it? Some kind of workaround available?
Please share, I can't distribute an app that messes the user's wifi.
