### ISSUE TITLE
Better error reporting when changing beacon characteristics

### ISSUE THREAD

**Issue by nutfox** [Estimote/Android-SDK#49]
Hi,

I've written a small android app to edit the proximity uuid of a beacon. When I tried to write it using this code to "12345":
connection.writeProximityUuid(uuid, new BeaconConnection.WriteCallback() {

I first got an error that the uuid must have an even number of characters - so I changed this to 123456 - unfortunately the onSuccess callback was never invoked - I can now no longer find the beacon - even if I set the region to "123456" - I get an error that it must be 32 characters.

This needs to be documented: What are valid values for the uuid? There should also be a validation error when the uuid provided is not valid.

**Comment by Poberro** [comment]
Closing. It is obsolete. Now UUID is set using as java.util.UUID object.
