### ISSUE TITLE
Android App is pretty unstable on background service

### ISSUE THREAD

**Issue by warlley** [Estimote/Android-SDK#67]
Hello, i am working on iBeacons development and i had some problemas with wifi adapter. When the iBeacon scan is running the wifi internet dont work, so i cant request info from internet when an iBeacon was detected. I did tried it on: Moto G, Moto X and Sony Xperia SP.

Another problem is when the scan is running on Android background, i need run this scan all the time to detect new iBeacons? That make the application pretty unstable, maybe because it uses a lot of phone process and memory. Somebody have any information or case about iBeacons Scan on Android background mode?

Thanks!

**Comment by sebascipocode** [comment]
Hi wiktor, on Moto G this issue still present with the last sdk version. there are any update about this possible bug?

**Comment by wiktor** [comment]
@sebascipocode We do not yet have good solution for that. Moto G is not the only device we are seeing problems with (fortunately it is only small subset of devices which have Bluetooth a bit broken).

**Comment by sebascipocode** [comment]
Thanks @wiktor,  I could see that on MotoG the issue only happened with Android 4.4.4 on Lolipop works fine for me. Maybe there are bug with this phone in these android version?
