### ISSUE TITLE
Service disconnected, crashed?

### ISSUE THREAD

**Issue by onskulis** [Estimote/Android-SDK#72]
Hello. I have following log out of my log cat.
08-13 14:02:26.030: E/EstimoteSDK(27742): com.estimote.sdk.BeaconManager$InternalServiceConnection.onServiceDisconnected:466 Service disconnected, crashed? ComponentInfo{com.my_app.test/com.estimote.sdk.service.BeaconService}

I start beaconManager inside remote service. App launches, starts my service, starts estimote service. I can quit app via HOME button, then I can close app when I hold home button and slide the app away. Service gets started again, and estimote service also. But when I close my app with "Go Back" button, I get this log. What could cause this behavior of estimote service?

**Comment by wiktor** [comment]
Closing this issue as remote processes as proven to work correctly.

**Comment by sanjeevcharan** [comment]
can any one share simple estimote beacon detection code in android at sanjay.narise@gmail.com
