### ISSUE TITLE
AndroidManifest.xml does not contain android.permission.BLUETOOTH or android.permission.BLUETOOTH_ADMIN

### ISSUE THREAD

**Issue by anvk** [Estimote/Android-SDK#80]
Nexus 4 device + Android Studio

Hi,
I created a tiny app based on the demo example. Running it on my Nexus4 USB attached device. But application constantly fails with the error:

E/EstimoteSDK﹕ com.estimote.sdk.BeaconManager.isBluetoothEnabled:182 AndroidManifest.xml does not contain android.permission.BLUETOOTH or android.permission.BLUETOOTH_ADMIN permissions. BeaconService may be also not declared in AndroidManifest.xml.

beaconManager.isBluetoothEnabled() constantly returns false

I double checked that my AndroidManifest.xml contains the following lines:

```
<uses-permission android:name="android.permission.BLUETOOTH" />
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN" />
<service android:name="com.estimote.sdk.service.BeaconService"
    android:exported="false"/>

<!-- Declaration that this app is usable on phones with Bluetooth Low Energy. -->
<uses-feature android:name="android.hardware.bluetooth_le"
    android:required="true"/>
```

I tried to rebuild the app multiple times but no success.
Disabled and enabled bluetooth on my phone multiple times.
Maybe I'm missing something stupid...

**Comment by aogooe** [comment]
Hi, I also met the same problem with you, I check in the whole project for a long time, the code without any problems.Do you find a solution on this issue?For help

**Comment by heypiotr** [comment]
Have you tried oskargustafsson's solution?
