### ISSUE TITLE
Encrypted uuid's for android sdk?

### ISSUE THREAD

**Issue by patcon** [Estimote/Android-SDK#81]
Wondering if this is coming to android sdk as well:

https://github.com/Estimote/iOS-SDK/issues/9#issuecomment-28573302

Also, any rough time-frame or setbacks? One month/year/release out? Thanks!

**Comment by laguiz** [comment]
+1 for this

**Comment by mgohin** [comment]
+1

**Comment by Marabita** [comment]
+1 for this

**Comment by nprokopic** [comment]
+1

Any updates on this?

**Comment by sasikanth513** [comment]
+1

**Comment by Poberro** [comment]
Secure UUID has been released in SDK version 0.9.
More info: https://github.com/Estimote/Android-SDK/releases/tag/0.9
