### ISSUE TITLE
setBackgroundScanPeriod or setForegroundScanPeriod not implemented?

### ISSUE THREAD

**Issue by johnnyzen** [Estimote/Android-SDK#9]
Hi there

setting either:

setBackgroundScanPeriod
setForegroundScanPeriod

doesnt seem to have any effect?

Can anyone advise?

**Comment by jorgetrejo** [comment]
@wiktor I want to set this variables
*beaconManager.setBackgroundScanPeriod(TimeUnit.SECONDS.toMillis(10), 0);
        beaconManager.setForegroundScanPeriod(TimeUnit.SECONDS.toMillis(10), 0);
, but its only can configure in onCreate, Exist a way to configure another place, and set variables when app is running ?

For example in:
` protected void startScanning() {
    toolbar.setSubtitle("Buscando salas cercanas...");
    adapter.replaceWith(Collections.<Nearable>emptyList());

    beaconManager.setNearableListener(new BeaconManager.NearableListener() {
      @Override public void onNearablesDiscovered(List<Nearable> nearables) {

        /*beaconManager.setBackgroundScanPeriod(TimeUnit.SECONDS.toMillis(10), 0);
        beaconManager.setForegroundScanPeriod(TimeUnit.SECONDS.toMillis(10), 0);
        */

        adapter.replaceWith(nearables);
        toolbar.setSubtitle("Salas cercanas encontradas: " + nearables.size());
      }
    });`
