### ISSUE TITLE
Android device as  a beacon [Question]

### ISSUE THREAD

**Issue by 90dend** [Estimote/Android-SDK#99]
Is there the way to use Android device as beacon?

**Comment by wiktor** [comment]
Yes, with Android L it is possible to act as a beacon. It is called peripheral mode.

See Android L changelog: https://developer.android.com/about/versions/android-5.0.html

**Comment by 90dend** [comment]
Can I realize it in my app with your SDK?

**Comment by wiktor** [comment]
At the moment no. You can use our iOS app to do so.
